### ISSUE TITLE
[builder] wrong UBERON version

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene-census#1017]
The schema 4.0.0 update did not bump the UBERON version used by the tissue mapper. Per the 4.0 schema, it should be v2023-09-05, but is currently using the schema 3 UBERON (v2023-06-28).

The pinned URL should be: https://github.com/obophenotype/uberon/releases/download/v2023-09-05/uberon.owl

CC: @brianraymor @pablo-gar

**Comment by bkmartinjr** [comment]
In addition, there appear to have been two changes to the `TissueMapper` (code copied into Builder from WMG, as we don't have a DRY package containing this). 

In the WMG version, the `HIGH_LEVEL_TISSUES` list:
* Deleted:   `"UBERON_0035328",  # upper outer quadrant of breast`
* Added:  `"UBERON_0000916",  # abdomen`

Should we make the same change in Census builder, alongside the above version change?

**Comment by pablo-gar** [comment]
yes please!
