### ISSUE TITLE
Return a checksum value for fetched Census data

### ISSUE THREAD

**Issue by hthomas-czi** [chanzuckerberg/cellxgene-census#1028]
This helps users ensure their data query was fetched successfully.

**User Quote**
> I’d like checksum for data downloaded to check for validity of downloads

**Comment by hthomas-czi** [comment]
@MaximilianLombardo To follow up with original requester

**Comment by MaximilianLombardo** [comment]
Additional context from the user:

> The problem initially arose from the university's computing system timing out before large datasets could be completely pulled from the census.

>The user found a workaround by fetching smaller sets of data (individual donors/samples) which reduced the need for pulling large datasets and was more successful.

>In cases where jobs do not finish, there is sometimes a partial file left, which often cannot be read, highlighting the need for a way to verify data completeness.

**Comment by bkmartinjr** [comment]
> ah ok - like specifically which function was being used

Yes, or alternatively a description of the access path/workflow.  Doesn't need to be super detailed, but there are different data paths in the system, some of which can be more easily solved than others.

**Comment by MaximilianLombardo** [comment]
great, followed up with the user for this info

**Comment by MaximilianLombardo** [comment]
The user responded that they were using `download_source_h5ad()` at the time.

**Comment by bkmartinjr** [comment]
In which case, it is more or less the same as chanzuckerberg/single-cell-data-portal#4392

My expectation is that if these are added, the source will be the data portal

CC @brianraymor

**Comment by brianraymor** [comment]
@pablo-gar - can this be closed as a duplicate of  chanzuckerberg/single-cell-data-portal#4392 per Bruce's [comment](https://github.com/chanzuckerberg/cellxgene-census/issues/1028#issuecomment-2027398398)? This is in the Q3 backlog. CC: @metakuni

**Comment by pablo-gar** [comment]
Yes, based on all the info provided by Harley anb Max it is certainly a duplicate of https://github.com/chanzuckerberg/single-cell-data-portal/issues/4392
