### ISSUE TITLE
get_embedding should not be obs biased

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/cellxgene-census#1048]
The `get_embedding` function was designed for obs embedding only (docs, parameters), but it also works for var embeddings.
Changes needed:
1. Rename `obs_soma_joinids` to `soma_joinids`. This is a breaking change, so consider whether we want to rename (and break) or do this via deprecation
2. Change the docs to remove the `obs` bias.

**Comment by pablo-gar** [comment]
Superseded by the embedding arguments of `get_anddata`
