### ISSUE TITLE
setup IAM role to support builder s3 uploads w/o user cred hack

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/cellxgene-census#109]
This will avoid having to cut & paste aws-oidc creds to a ec2 instance, which is a security risk.

**Comment by bkmartinjr** [comment]
which account will be enabled to write to the bucket?  An IAM role opens up security risks as well, as anyone with access to the other account is now able to mutate the bucket....

**Comment by ebezzi** [comment]
As Bruce pointed out, if the bucket lives in prod, we shouldn't create an IAM in dev for it that has _write_ permissions. We should rather run the builder in the prod account, but this might not be desirable either until we have a stable release.

**Comment by bkmartinjr** [comment]
> As Bruce pointed out, if the bucket lives in prod, we shouldn't create an IAM in dev for it that has write permissions. We should rather run the builder in the prod account, but this might not be desirable either until we have a stable release.

I was mostly pointing out that the security will be a compromise in some way until such time as we run the jobs in a more controlled environment.  That seems like a H223 goal from my viewpoint (eg, after we containerize and automate the build).  But we should capture input from @atolopko-czi and see what he thinks.

**Comment by ebezzi** [comment]
I agree with you. Also, creating an IAM role with write permissions to a prod bucket will be significant work since it requires cross-account permissions and the one we have right now only gives read access (as it should).

**Comment by atolopko-czi** [comment]
Overall, this issue is simply tracking the need to ensure that however we're using EC2 instances now, we're not doing anything terribly insecure. Concerns were voiced that our aws-oidc should be reconsidered. So we should probably just reach out to Infra Sec for their suggestions on which solution is the lesser (security) evil.

Maybe aws-oidc creds is acceptable, maybe not. Alternately, if the IAM role only allows S3 Put and Get, but not Delete, maybe it's fine to run the builder in `prod` account now.

**Comment by pablo-gar** [comment]
Related to Trust Review #279 we may have better guidance after that is completed

**Comment by ebezzi** [comment]
Fixed by [this commit](https://github.com/chanzuckerberg/single-cell-infra/commit/f907a8303b3ef886c416d4944b69e6aae07c760a). Closing.
