### ISSUE TITLE
Remove  "EFO:0030080 - 10x transcription profiling" from the accepted assays of Census

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#1105]
Remove "EFO:0030080 - 10x transcription profiling" from the accepted assays of Census 

- [ ] Remove from [census_accepted_assays.csv](./docs/census_accepted_assays.csv) and do a schema bump to 5.0.1
- [ ] Remove from builder code

see https://czi-sci.slack.com/archives/C024HCSH9PT/p1713197913630429

**Comment by jahilton** [comment]
There are other very broad terms currently on the accepted assay list that may run into the same issue as EFO:0030080. That is, a submission with that assay value may simply have that as a placeholder while a specific EFO term is created.

- random RNA-Seq across whole transcriptome
- RNA-seq of coding RNA from single cells
- RNA-seq of non coding RNA from single cells
- tag based single cell RNA sequencing
- full length single cell RNA sequencing
- single-cell RNA sequencing
- single nucleus RNA sequencing
- full length single nucleus RNA sequencing
- tag based single nucleus RNA sequencing
