### ISSUE TITLE
Work with Tiledb to produce a good design proposal for shape/reshape feature for Tiledb-SOMA

### ISSUE THREAD

**Issue by prathapsridharan** [chanzuckerberg/cellxgene-census#1107]
## Description

The current proposal for this feature is tracked in this document:

https://docs.google.com/document/d/1lzJrdozpvHTrAyL5ccz8v-OBkf6MK3x1lAQeYnmJkeM/edit

The goal of this ticket is to work closely with Tiledb to produce a design for "shape/reshape" feature for `Tiledb-SOMA` that is easy to use, consistent in semantics and performant in operations. Specifically, we want to ensure that the feature won't introduce any problems in Census or Census-Spatial.

Part of the collaboration might involve writing some prototyping code from a client perspective (users of `Tiledb-Soma`) such that the API are consistent (ex: API for denseNDArray and sparseNDArray behave as expected) and performant.

For context, here are some older issues and design docs to give an idea of the complexity and surface area affected by this proposal:

1. Older design doc: https://docs.google.com/document/d/1iVTH7-h5UD7JMsOKudMGFl27Mc21sD-jhZYb5JhVSZw/edit#heading=h.8ku31f93ojzx
2. Github issues filed in regards to this feature: https://github.com/single-cell-data/TileDB-SOMA/issues/1971

**Comment by pablo-gar** [comment]
Completed
