### ISSUE TITLE
Building from dataset manifest does not set dataset metadata

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/cellxgene-census#111]
The `census["census_info"]["datasets"]` table (metadata) does not have values for the below columns when the census is built from a manifest file.

* collection_id
* collection_name
* collection_doi
* dataset_title

- [ ] The validation step should check for the existence of these metadata. REQUIRED.
- [ ] Make the manifest build equivalent to the API-based build. OPTIONAL. 

The 2nd item is optional because, pragmatically, we can get by with simply knowing not to use `--manifest` for census builds that will be released. This could simply be documented and/or we could output a warning on usages of `--manifest`. If we're not satisfied with that, then one of the following design changes could be implemented: 
1. Explicitly request the required metadata from the Discover API for each dataset specified in the manifest file
2. Require the metadata be provided in the manifest file. This solution makes more sense if we also have the builder _output_ a manifest during its dataset acquisition step. This would allow re-running the builder properly from a manifest file and the existing H5ADs, in cases where a subsequent abort of the builder requires a restart.

**Comment by pablo-gar** [comment]
> The validation step should check for the existence of these metadata.

To me this is may be more than low-priority imo. The way we identified this was by a failing notebook, correct?

**Comment by atolopko-czi** [comment]
> To me this is may be more than low-priority imo. The way we identified this was by a failing notebook, correct?

I figured that if we always build census in the normal fashion, i.e., with full H5AD download and not using the special manifest-based build, then this won't occur. So it's avoidable. So I think the high-prio piece should just be adding the validator check.

**Comment by atolopko-czi** [comment]
Yes, Manifest should only used for testing. Can close.
