### ISSUE TITLE
Publish Census LTS release, June 2024 

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#1139]
Epic to organize tasks required to publish the upcoming Census LTS data release.

Schedule:

- May 20th will be the candidate weekly build for the  LTS data release
- May 21-31: 
   - Train models and QC
   - Contact model contributors for interest in new embeddings.
- June 1st-21st: 
   - Upload embeddings, QC
   - Update notebooks/docs
   - Prepare marketing.
- June 24-25
   - Promote data to LTS
   - Push marketing

**Comment by ivirshup** [comment]
@pablo-gar is this closable now?

**Comment by pablo-gar** [comment]
yes
