### ISSUE TITLE
Draft schema for `collection_doi_label` of `census["census_info"]["dataset"]`

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#1179]
see https://czi-sci.slack.com/archives/C023Q1APASK/p1716245770988479 for reference.

# Schema changes

[...]

#### Census table of CELLxGENE Discover datasets – `census_obj["census_info"]["datasets"]` – `SOMADataFrame`

All datasets used to build the Census MUST be included in a table modeled as a `SOMADataFrame`. Each row MUST correspond to an individual dataset with the following columns:

<table>
<thead>
  <tr>
    <th>Column</th>
    <th>Encoding</th>
    <th>Description</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>citation</td>
    <td>string</td>
    <td rowspan="7">As defined in the CELLxGENE <a href="https://api.cellxgene.cziscience.com/curation/ui/">Discover API data schema</a>.</td>
  </tr>
  <tr>
    <td>collection_id</td>
    <td>string</td>
  </tr>
  <tr>
    <td>collection_name</td>
    <td>string</td>
  </tr>
  <tr>
    <td>collection_doi</td>
    <td>string</td>
  </tr>
  <tr>
    <td>collection_doi_label</td>
    <td>string</td>
  </tr>
  <tr>
    <td>dataset_id</td>
    <td>string</td>
  </tr>
  <tr>
    <td>dataset_title</td>
    <td>string</td>
  </tr>
  <tr>
    <td>dataset_h5ad_path</td>
    <td>string</td>
    <td>Relative path to the source h5ad file in the Census storage bucket.</td>
  </tr>
  <tr>
    <td>dataset_total_cell_count</td>
    <td>int</td>
    <td>Total number of cells from the dataset included in the Census.</td>
  </tr>
  <tr>
    <td>dataset_version_id</td>
    <td>string</td>
    <td>As defined in the CELLxGENE <a href="https://api.cellxgene.cziscience.com/curation/ui/">Discover API data schema</a>.</td>
  </tr>
</tbody>
</table>

[...]

### Version 2.1.0

* Adds `collection_doi_label` to "Census table of CELLxGENE Discover datasets – `census_obj["census_info"]["datasets"]`"

[...]

**Comment by brianraymor** [comment]
Nit. I would not use "crossref" in the name. It's just the mechanism used to acquire publication metadata.

The citation is an internal design based on that metadata.

How about `collection_doi_label`to differentiate from the dataset citation and to self-document that it's related to `collection_doi`.

**Comment by pablo-gar** [comment]
That's a good name. Updated.

**Comment by pablo-gar** [comment]
Updated since the string will be directly fetched from Discover API

**Comment by pablo-gar** [comment]
Completed by #1200
