### ISSUE TITLE
Census Builder should ingest to CXG schema 5.1.0 datasets

### ISSUE THREAD

**Issue by prathapsridharan** [chanzuckerberg/cellxgene-census#1194]
- [ ] Modify builder to update pins and constants to be ready for `5.1.0`
- [ ] Ensure all builder automated tests pass
- [ ] Run the builder in the `census-dev` environment and create a test build
- [ ] Run manual QA against the test build by running several queries using api
- [ ] Update references to dataset schema version and associated links in the Census schema document.
- [ ] Update changelog of Census schema
- [ ] Merge the change to `main`
- [ ] Kick off an out-of-cycle `prod` census build

**Comment by pablo-gar** [comment]
@prathapsridharan Please add 

- [] Update references to dataset schema version and associated links in the Census schema document
