### ISSUE TITLE
What is the difference between tissue and tissue_general

### ISSUE THREAD

**Issue by Alex2975** [chanzuckerberg/cellxgene-census#1216]
Dear Authors,

Could you please share what is the difference between the tissue and tissue_general? Thank you very much.

**Comment by pablo-gar** [comment]
Hi @Alex2975, 

See our [schema document](https://github.com/chanzuckerberg/cellxgene-census/blob/main/docs/cellxgene_census_schema.md#definitions) for specific definitions.

> - tissue – original tissue annotation.
> - tissue_general – high-level mapping of a tissue, e.g. "Heart" is the tissue_general of "Heart left ventricle" .

**Comment by Alex2975** [comment]
Got it, thank you very much, @pablo-gar .

**Comment by Alex2975** [comment]
@pablo-gar , would it be possible to extract both raw and normalized expressions to one h5ad file? 
Can I use the following code, so that I have both raw expression and normalized expression in one h5ad? Thank you again. 

with cellxgene_census.open_soma(census_version = 'latest') as census:
    adata = cellxgene_census.get_anndata(
        census = census,
        organism = "Homo sapiens",
        obs_value_filter="disease == 'normal' and is_primary_data == True",
        X_name = 'normalized',
        X_name = 'raw'
    )

**Comment by pablo-gar** [comment]
Yes, you can use the `X_layers` argument

```
adata = cellxgene_census.get_anndata(..., X_name = "raw", X_layers=["normalized"])
```

**Comment by Alex2975** [comment]
Great, thank you so much, @pablo-gar .
