### ISSUE TITLE
Bulk download h5ad data with filters [R]

### ISSUE THREAD

**Issue by myushen** [chanzuckerberg/cellxgene-census#1217]
Hi, can you please provide guidance on how to download h5ad in bulk with filters of interest in R? 

TileDB-SOMA API supports both Python and R, but the documentation only provides Python examples. I tried a similar syntax in R, but it reports that the URI is not a TileDB SOMA object. Am I missing something obvious?
```
uri = "s3://cellxgene-census-public-us-west-2/cell-census/2023-07-25/soma/"
census <- tiledbsoma::SOMAOpen(uri = uri)
```

Thanks for your help.

**Comment by pablo-gar** [comment]
Hi @myushen 

Our doc-site has a link to [R API & tutorials](https://chanzuckerberg.github.io/cellxgene-census/r/index.html). You can find more information about R usage there.

You will only be able to download the **original h5ads as deposited by contributors** via [`download_source_h5ad`](https://chanzuckerberg.github.io/cellxgene-census/r/reference/download_source_h5ad.html) using the `dataset_id` of your data of interest.

If you want to download specific slices of Census after filtering, you can only do so for `Seurat` or `SingleCellExperiment` objects.
