### ISSUE TITLE
cellxgene-census times out running through a proxy server

### ISSUE THREAD

**Issue by kgweiss** [chanzuckerberg/cellxgene-census#1256]
## Motivation

Why is this work important to engineers? - Quick start program works on our cluster login nodes but not on compute nodes. Compute nodes access to Internet is via proxy. Login nodes have direct access to Internet.

## Definition of Done

What should the end result look like? What will have been changed? - Having the quickstart Python code run to completion on a proxied compute node on my cluster.

## Tasks

Detail the specific tasks that can be used to accomplish the desired changes.
If detailed steps cannot be provided at this time, please file a [Tech Proposal](https://docs.google.com/document/d/1o2vuvl-kXwRJN1nBoPzJS_MAQgDGYnjmPZWa4qRDi-I/edit#heading=h.7dvzhm7gqc3v) instead.

Procedure:
1. installed census API following the instructions found here: https://github.com/chanzuckerberg/cellxgene-census/blob/main/docs/cellxgene_census_docsite_installation.md
2. activated the environment using python 3.11.5
3. created Python script
---  start ---
import cellxgene_census
import tiledb

with cellxgene_census.open_soma(census_version="2024-07-01") as census:

    # Reads SOMADataFrame as a slice
    cell_metadata = census["census_data"]["homo_sapiens"].obs.read(
        value_filter = "sex == 'female' and cell_type in ['microglial cell', 'neuron']",
        column_names = ["assay", "cell_type", "tissue", "tissue_general", "suspension_type", "disease"]
    )

    # Concatenates results to pyarrow.Table
    cell_metadata = cell_metadata.concat()

    # Converts to pandas.DataFrame
    cell_metadata = cell_metadata.to_pandas()

    print(cell_metadata)
    census.close()
--- stop ---
4. ran on login node w/out issue. Tried on compute node with proxy and received the message:

Traceback (most recent call last):
  File "/gpfs/accounts/support_root/support/kgweiss/cellxgene/test3.py", line 4, in <module>
    with cellxgene_census.open_soma(census_version="2024-07-01") as census:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/accounts/support_root/support/kgweiss/cellxgene/venv/lib/python3.11/site-packages/cellxgene_census/_open.py", line 260, in open_soma
    return _open_soma(locator, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/accounts/support_root/support/kgweiss/cellxgene/venv/lib/python3.11/site-packages/cellxgene_census/_open.py", line 85, in _open_soma
    return soma.open(locator["uri"], mode="r", soma_type=soma.Collection, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/accounts/support_root/support/kgweiss/cellxgene/venv/lib/python3.11/site-packages/tiledbsoma/_factory.py", line 125, in open
    obj: TileDBObject[_Wrapper] = _open_internal(  # type: ignore[valid-type]
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/accounts/support_root/support/kgweiss/cellxgene/venv/lib/python3.11/site-packages/tiledbsoma/_factory.py", line 156, in _open_internal
    handle = opener(uri, mode, context, timestamp)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/accounts/support_root/support/kgweiss/cellxgene/venv/lib/python3.11/site-packages/tiledbsoma/_tdb_handles.py", line 80, in open
    else tiledb.object_type(uri, ctx=context.tiledb_ctx)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tiledb/libtiledb.pyx", line 3706, in tiledb.libtiledb.object_type
  File "tiledb/libtiledb.pyx", line 348, in tiledb.libtiledb.check_error
  File "tiledb/libtiledb.pyx", line 342, in tiledb.libtiledb._raise_ctx_err
  File "tiledb/libtiledb.pyx", line 327, in tiledb.libtiledb._raise_tiledb_error
tiledb.cc.TileDBError: [TileDB::S3] Error: Error while listing with prefix 's3://cellxgene-census-public-us-west-2/cell-census/2024-07-01/soma/__schema/' and delimiter '/'[Error Type: 99] [HTTP Response Code: -1] : curlCode: 28, Timeout was reached

Please advise. Thanks.

**Comment by ivirshup** [comment]
Hey @kgweiss, thanks for opening an issue.

I think that this looks like an issue with a firewall blocking access to s3. Can you try running something like:

```python
import s3fs

fs = s3fs.S3FileSystem(anon=True)
fs.ls("s3://cellxgene-census-public-us-west-2")
```

?

If you're also getting timeouts from this snippet then I think you'll need to ask your HPC sysadmin about this.

**Comment by kgweiss** [comment]
@ivirshup Thanks for the followup. I ran an interactive session on my cluster and your test appears to have been able to reach the S3 bucket:

```
> $ python
> Python 3.11.5 (main, Oct 31 2023, 12:36:43) [GCC 10.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import s3fs
> >>> fs = s3fs.S3FileSystem(anon=True)
> >>> fs.ls("s3://cellxgene-census-public-us-west-2")
> ['cellxgene-census-public-us-west-2/cell-census']
```

Thoughts?

**Comment by ivirshup** [comment]
If you also ran `cellxgene_census.open_soma(census_version="2024-07-01")` on this session, that would error with a timeout?

Do you normally have to do anything from your compute nodes to redirect requests through the proxy? Is there a `HTTPS_PROXY` variable set or anything?

If so, I'm thinking that you need to tell tiledb that it needs to be accessing the census via a proxy. You can do this with:

```python
import cellxgene_census

config = {
    "vfs.s3.proxy_host": ..., "vfs.s3.proxy_port": ...
}
census = cellxgene_census.open_soma(tiledb_config=config)
```

Where you fill in the `proxy_host` and `proxy_port` info

**Comment by kgweiss** [comment]
Isaac,

That was the key. Defining the proxy host and proxy port and setting the tiledb_config option.

Thank you very much for your assistance. You rock!!!

Cheers,
Ken

**Comment by ivirshup** [comment]
Np, happy to help!
