### ISSUE TITLE
Stop auto-closing issues

### ISSUE THREAD

**Issue by ivirshup** [chanzuckerberg/cellxgene-census#1268]
## Motivation

The pace set by autoclave does not match the number of engineers we actually have. Also it's nicer for a human to make this call, and is not a good experience for potential contributors

## Definition of Done

We stop auto-closing PRs

We can either remove this all together, or we can just turn off closing.

## Tasks

* Remove `.github/workflows/close-stale-prs.yml` to totally remove
* Set `days-before-pr-close: -1`  to prevent PRs from being closed

Any preference on these two? @pablo-gar @ebezzi

**Comment by ebezzi** [comment]
Totally remove
