### ISSUE TITLE
Fix docs for data loaders

### ISSUE THREAD

**Issue by ivirshup** [chanzuckerberg/cellxgene-census#1291]
In https://github.com/chanzuckerberg/cellxgene-census/issues/1289#issuecomment-2386551003 @yanwu2014 noted that the docs still say we are returning the `soma_join_ids` per batch in all cases, even though we removed that behavior. We can see that here:

![image](https://github.com/user-attachments/assets/ad69c74c-1543-466a-b96a-4f98b3e50c7c)

We should fix that.

**Comment by yanwu2014** [comment]
Thank you!
