### ISSUE TITLE
Add approved assays to accepted assay list

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/cellxgene-census#1302]
A number of assays were approved for submission and now have EFO terms, so they can be included in census_accepted_assays & the data can be included in Census
term_id | label
-- | --
EFO:0022600 | Parse Evercode Whole Transcriptome v1
EFO:0022601 | Parse Evercode Whole Transcriptome v2
EFO:0022602 | Parse Evercode Whole Transcriptome v3
EFO:0022839 | STORM-seq
EFO:0022606 | 10x gene expression flex
EFO:0022845 | modified STRT-seq
EFO:0022846 | 5' STRT-seq

**Comment by ivirshup** [comment]
@jahilton, is STORM seq the only full-length assay here?

**Comment by jahilton** [comment]
Yes
Also of note, 10x flex is probe-based

**Comment by ivirshup** [comment]
Have we had any other platforms that are probe based in census?

**Comment by ivirshup** [comment]
Also, do you have any counts on how many cells we have with those technologies? I did a build on my PR, and want some numbers I can compare in spot checks to make sure everything is working as expected.

**Comment by ivirshup** [comment]
The only difference I am immediately seeing is that all the `sci-RNA-seq` data now seems to be labelled `sci-RNA-seq3`

**Comment by jahilton** [comment]
We have "BD Rhapsody Targeted mRNA" - I don't know offhand how that compares to 10x flex
I believe some Visium will be probe-based, but not the v1 that is currently accepted

The only assay in this ticket with data currently in CELLxGENE is "modified STRT-seq" in [this Collection](https://cellxgene.cziscience.com/collections/1e313b15-4aca-4e5a-94a3-1093c4c42abd) - assay update specified in the [ontology bump issue](https://github.com/chanzuckerberg/single-cell-curation/issues/1023)
The rest were added as they pertain to in progress submissions

**Comment by ivirshup** [comment]
Ah, I didn't make the connection that this was part of the 5.3 update. That explains why I'm not seeing that assay in the curation API or census.
