### ISSUE TITLE
Include a high level term for cell types in the Cell Census

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#17]
It would be helpful if the `cell type` annotation had a high-level ontology term mapping, similar to how the `tissue` and `tissue_ontology_term_id` have a 1-to-1 mapping to a high-level tissue for increased usability of the Cell Census: `tissue_general` and `tissue_general_ontology_term_id`.

This was originally suggested by Angela Pisco

**Comment by brianraymor** [comment]
And we have prior art for cell types from _filter with ontology awareness_.

**Comment by atolopko-czi** [comment]
@pablo-gar `tissue_general` is already in the census ([Core code](https://github.com/chanzuckerberg/cell-census/blob/main/tools/cell_census_builder/tissue_mapper.py#L128)). OK to close this issue or is there more to it?

**Comment by pablo-gar** [comment]
This is a request that came from Angela and it relates to having `cell_type_general` or something alike.

**Comment by bkmartinjr** [comment]
This issue is in regard to cell type, not tissue type - it is not resolved.

**Comment by atolopko-czi** [comment]
> This issue is in regard to cell type, not tissue type - it is not resolved.

rewrote description to aid my next reading. :)

**Comment by lubianat** [comment]
@pablo-gar is this something you would like to be provided by the Cell Ontology? Or something you'd prefer to curate internally? 

We were discussing having a related broad 'category' for each term in this ticket: 
https://github.com/INCATools/ontology-development-kit/issues/859#issuecomment-1529495729

**Comment by pablo-gar** [comment]
@lubianat we decided to keep this work in house for the time being. Thanks for the reference

**Comment by pablo-gar** [comment]
Related https://github.com/chanzuckerberg/cellxgene-census/issues/883

**Comment by pablo-gar** [comment]
See suggested initial minimal solution https://github.com/chanzuckerberg/cellxgene-census/issues/1029#issuecomment-2108164017

**Comment by pablo-gar** [comment]
Minimal solution implemented via Cell Ontology Guide #1163
