### ISSUE TITLE
Define "how to contribute" guidelines

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#216]
We need to define IF and HOW external contributors can/will contribute to the development of this repo.

First we need to define the IF and consider the following:

- Define a successful contribution would look like, and assess the confidence that we could communicate our expectations to potential contributors.
- Understand of the cost of discussing, reviewing, and maintaining contributed code. Assess if we can incur the cost at this stage.
- Investigate and assess if we have the resources required to support the contributions.

**Comment by brianraymor** [comment]
Closed per triage.
