### ISSUE TITLE
Write FAQs

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#220]
- [x] Brainstorm to come up with a set of FAQ
- [x] Write them up and host them in `md` under `docs`

Please list any candidate FAQs as comments in this thread

**Comment by pablo-gar** [comment]
Initial Candidates:

* Where are the Cell Census data buids hosted?
* How can I increase performance? 
* Can I use conda to install the Cell Census?

**Comment by pablo-gar** [comment]
Other candidates:

- Why should I use the Cell Census?
- Why does the Cell Census not have a normalized layer or embeddings?
- How does the Cell Census differentiate from other services?
- How can I ask for support?
- How can I ask for new features?
- How can I contribute my data to the Cell Census?

**Comment by Ivana-Jelic** [comment]
Can one query human and mouse data in a single query?

**Comment by pablo-gar** [comment]
From #94 

Why do I get an ArraySchema error when opening the Census?

**Comment by pablo-gar** [comment]
Done #386
