### ISSUE TITLE
builder unit tests mock ontology download

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/cellxgene-census#235]
## Motivation

Removes a remote service dependency during unit tests. Speeds up tests.

## Definition of Done

No remote calls are made during unit tests.

## Tasks

- [ ] Mock the call to `owlready2.get_ontology(uberon_ontology)`

**Comment by brianraymor** [comment]
Per long term plan (ontology service replaces dependents querying ontologies) this will not be relevant.
