### ISSUE TITLE
Cell Census unique and traceable cell identifiers

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#25]
TLDR - for reproducibility and increased usability of the Cell Census, unique cell identifiers that are stable over builds would be ideal. However this poses technical difficulties.

Pablo

> This means that 
> all cells must have a unique and traceable ID

Bruce Martin

> I don't think we have sufficient upstream guarantees to make that plausible (or at least not to make it easy).
> There are two issues:
> * duplication of cells - the new schema makes weak promises about the is_primary value, so there may be duplicates of any given cell.
> * the upstream (source) data lacks an unique and explicit cell identifier within a dataset.  The cellxgene schema doesn't specify such a thing as I read it.
> The lack of upstream identifier is the biggest issue IMHO. If we had a unique identifier in the upstream datasets, then we could concatenate it with the dataset_id and create a globally unique cell identifier.
> I can think of three possible solutions:
> 1) upstream (per-dataset) cells are given a unique identifier within each dataset during creation.
> 2) we use the cell position (iloc) in the dataset as the intra-dataset cell identifier, which means any future curation must be extremely careful to not reorder.  Example: any deletions must leave a "hole", there can be no re-ordering, etc.
> 3) we computationally generate a usually unique pseudo-ID.  For example, hash the X.raw[cell, :] values, which will commonly be unique.  If we also throw in a hash of the obs metadata, we are almost certainly unique.
> There are pros/cons to all.  OTOMH:
> (1) would be the most durable, but at some level pushes the issue upstream to the re-curation processes.  Likely requires validation tools for any re-curation/re-mastering.
> (2) is easy to screw up because the ID is implicit.  Likely requires similar tools/validation to (1).
> (3) is computation

Jason Hilton

> this seems independent of cell ids
> if there are duplicates, then maybe cell ids hint at the duplication (likely contain the barcode), but 1) that's not always going to be the case for duplications and 2) matching barcodes certainly won't always mean duplicate cells

Bruce Martin

> I think the question is if identity can be used to de-dup.
> 
> Or rather, is it a cell ID (in the biological sense of a cell), or a "data row ID" in side a dataset?
> 
> Or something in between?

Jason Hilton

> No - identity cannot be used to de-dup. Like with donor_id, you're going to have 12 Donor1's across the data corpus that are not dups, only increase that by several factors
> 
> nobody "names" their cells in any biological sense because nobody talks/writes about individual cells.

Bruce Martin

> At the risk of being unhelpful (sorry!), why are we trying to introduce a first class cell identity if nobody talks/writes about individual cells? What is the use case?
> 
> I am very likely missing some critical concept...I thought the whole point was ability to trace across census releases, and/or dedup.
> 

Jason Hilton

> "a first class cell identity" - I don't know what that is. Who does? Where is it documented w/ requirements, etc?

Bruce Martin

> Sorry, I'm not trying to be argumentative. This came from a conversation I had with Pablo - i.e., my own understanding of what he was trying to achieve. So I'll let him speak for himself rather than trying to represent it :-)
> 
> Pablo, open mike!

------------

Jason Hilton

> unique - YES. the schema doesn't explicitly state this but validator will fail if obs.index is not unique
> 
> explicit - what do you mean by this?

Brian Raymor

> @[bruce@chanzuckerberg.com](mailto:bruce@chanzuckerberg.com) - your serve.

Bruce Martin

> this ad hoc test is true as far as it goes, but it is not codified in the schema, and AnnData has been making rumblings about changing it. So it is more a useful coincidence than a data model :-)
> 
> There is also, AFAIK, zero guarantees that this obs.index value will have continuity across re-mastering, etc.
> 
> The more important point in the highlighted text is "explicit ...", not "unique....".  I'd just hate to see us tie a lot of downstream assumptions to such a weak, ad hoc, contract....

Jason Hilton

> uniqueness is codified in the schema - it's just not written down yet
> 
> "continuity across re-mastering" - can you explain this requirement?
> 
> "downstream assumptions" - what assumptions are based on cell IDs?

Bruce Martin

> "continuity" - are cell identities preserved over time. Over multiple dataset updates (eg, the recent schema changes), over re-publication of the census, etc. Or are they only a contract at a given point in time or release (or container)
> 
> "downstream assumptions" - are identities strings, ints, of a common format, etc? The current dataset IDs are a rich stew of stuff, some of it costly (i.e., giant strings) to store and operate on, different by pipeline, etc. Downstream users likely want a single, concise ID (eg, an int64).
> 
> IMHO, we would be far better off adding our own ID and not rely on user-provided indices. We could use the assumptions above to implement it if that is convenient.

------------

Jennifer Yu-Sheng Chien

> The datasets that we anticipate getting updates of additional cells are KPMP and Tabula. 
> 
> Would the cells in all the datasets in a collection be required to have the unique cell identifier? If so, would it then be that the is_primary_data==True dataset will contain the unique cell identifier, and that identifier will be preserved across the datasets within that collection?

**Comment by brianraymor** [comment]
@pablo-gar to review with Lattice and close if not actionable.

**Comment by pablo-gar** [comment]
More discussion 

@jychien

> As an FYI, I’ll outline the issues that came up during the May2022 Integration workshop, where one of the tasks for integrators was to subset, create, and annotate a 2 million cell dataset from a total of 11 million.
> There was not a clear way to compare final annotations between the groups, because each group had selected different 2 millions cells and there was no persistent cell identifiers. Some groups reassigned cell identifiers or added a new suffix.
> We could not definitively trace the integrated cell back to a cell in original dataset to compare annotations. This was because people were not consistent in keeping the original cell identifier.
> Would it be possible to maintain the original cell identifier in obs as cell metadata? I see soma_joinid, but not the original index of obs.

@atarashansky 

> I was speaking to [@atolopko](https://czi-sci.slack.com/team/U5NQHMVAP) about the exact same topic as I ran into the same issue that [@jychien](https://czi-sci.slack.com/team/WN9AUJ0NT) described. I have two thoughts on this topic:
>
> 
> - Wouldn't it be possible to treat soma_joinid as unique identifiers per cell as long as it is paired with the cell census version it came from?
>    - Nevermind, this would not yield consistent cell identifiers between builds.
>    - But, you would be able to recover the cell metadata from census as long as your h5ad's have the soma_joinid's and the census build version it came from. This is captured in [this issue](https://github.com/chanzuckerberg/cellxgene-census/issues/440).
> - Also, I second [@jychien](https://czi-sci.slack.com/team/WN9AUJ0NT)’s suggestion to keep the original cell IDs as a column in the census. We can concatenate dataset_id and the original cell IDs to obtain unique identifiers. Would that work for maintaining consistent cell identifiers between builds?
>
> Related to Bruce's point about duplication of cells in the linked thread,
>
> > duplication of cells - the new schema makes weak promises about the is_primary value, so there may be duplicates of any given cell. 
>
> Would primary datasets have different dataset IDs than their non-primary subsets? If so, then concatenation of dataset_id and original cell ID would solve that issue.
> 
> Ah, actually, I just read further and saw this point by Bruce:
> 
> > the upstream (source) data lacks an unique and explicit cell identifier within a dataset. The cellxgene schema doesn't specify such a thing as I read it.
> > The lack of upstream identifier is the biggest issue IMHO. If we had a unique identifier in the upstream datasets, then we could concatenate it with the dataset_id and create a globally unique cell identifier.
> 
> Right, if the original cell IDs are removed during the data ingestion process then the proposed solution would not work.

From @bkmartinjr 

> Couple of additional ramblings:
> 
> - the "offset" into the original H5AD obs really isn't unique either, as we could in theory rewrite the H5AD at some point (e.g., remove a cell).  So the tuple of "dataset_id" and "obs iloc" isn't an ID
> - Last I looked, the the "original cell ids" in the H5AD were not particularly helpful as we don't push any requirements upstream to submitters about their meaning.  Has this changed?
> - during initial curation (ingestion of the original data, where we assign is_primary_data, etc), we could generate a unique CZI-assigned global id for any cell (e.g., a UUID or whatever).   It would really be a "record ID" not a "cell ID", as we have no way to know what the obs entry really matches in the real world

From @atarashansky 
 
> I think it's super important to have consistent cell identifiers between builds, and, in my "not a PM" opinion, difficult solutions should not be a deterrent to their implementation.
> Let's say we have a reannotation jamboree, where we use the census data to fine-tune and improve the quality of our annotations. For the purpose of the jamobree, the organizers are diligent enough to make sure that everyone uses a specific version of the census (e.g. not latest). This process lasts a couple weeks until we are satisfied with the new annotations.
> 
> - Note: Why use census for the annotations? Reannotation can be much more effective when done in an integrated space. Reannotating each of our 777 datasets independently is also simply not practical.
> 
> So how do we map the updated census annotations back to the source datasets so future census builds can incorporate the new annotations? It's impossible without unique cell identifiers.

From @jychien

> > Last I looked, the the “original cell ids” in the H5AD were not particularly helpful as we don’t push any requirements upstream to submitters about their meaning.  Has this changed?
>
> There is currently not anything documented in the schema in regards to the obs index, and therefore is not checked in validation.  We’ve seen a wide spectrum of values, so I don’t think there is any value other than it being a unique identifier for the cell within the h5ad. 

@pablo-gar 

> This is almost certainly over-simplified but perhaps this approach could stimulate more discussion about moving towards consistent cell IDs.
> As we have total control over the schema, I propose a schema update that reads as follows:
>
> > _All cells in future datasets must be assigned a unique, immutable cell ID. Revisions must not alter the IDs of remaining cells after filtering, and newly added cells must be assigned unique, immutable cell IDs. Cell IDs will be stored in a mandatory cell_identifier column._
?
> When it comes to upgrading existing datasets in our corpus, I propose the following (automated) one-time upgrade:
>
> > _The integer indices of all existing datasets will be stringified and stored in a cell_identifier column. Further revisions applied to these datasets will follow the policy set forth by the CELLxGENE schema (above)._
> 

@pablo-gar 

> Thanks Alec. I agree with you on the importance of these IDs (I was the one with the initial push on them, then I had a few convos with Bruce around this and then the rest of the team).
> Aside from importance, two other aspects to consider: priorities and sizing which both come into play for us to know what to work on. And the last piece is at what level of Discover this needs to be addressed. There are a lot suggestions to the Census that ideally belong to the h5ad schema. (cc 
> [@Brian Raymor](https://czi-sci.slack.com/team/UA22DUVEU)
> )
> The topic has not been discarded yet, but it was not a priority and in combination with its sizing it is currently in a backlog.
> It would be very helpful if you both provide a summary of your thoughts in the ticket to capture all of the great feedback included here.

@bkmartinjr 

> We’ve seen a wide spectrum of values, so I don’t think there is any value other than it being a unique identifier for the cell within the h5ad
> Assuming my memory is not faulty (50%? :slightly_smiling_face:), one can't assume index IDs are unique in an H5AD (unless we validate for that).   Pandas does not enforce it, and last I checked, neither did AnnData.  AnnData has support to deal with this case, such as [AnnData.obs_names_make_unique](https://anndata.readthedocs.io/en/latest/generated/anndata.AnnData.obs_names_make_unique.html), and the index_unique flag in AnnData.concatenate.
> Is there any benefit in pushing this upstream, vs just having our curation process assign an ID?  The latter would let us make some choices that might simplify processing/implementation (e.g., data type for the ID, etc).

@pablo-gar 

> From my conversations with Bruce, the biggest imo challenge is how to ensure traceability of IDs. In principle you’d want ID X to correspond to the same cell over versions of a dataset (since we have revisions), there is no way we can 100% validate this, and thus we would need to pass on the responsibility to the curators

@atarashansky 

> I think that's a great point. It definitely seems difficult to catch with automated validation. No real solution here to the traceability concern when it comes to catching violations of schema requirements for cell_identifier, but here are more ramblings in the hopes of stimulating discussion...
> I'm still an infant when it comes to the complexity of schema management and curation, but I'm wondering how much surface area there is for curator or submitter error in this case and how much we are willing to tolerate (question for [@Brian Raymor](https://czi-sci.slack.com/team/UA22DUVEU) and [@jahilton](https://czi-sci.slack.com/team/WN1696CG1)).
> As one example, how do we ensure that the same metadata rows correspond to the same gene expression rows over revisions? That also seems impossible to validate (though I do recall cases where we caught this manually due to completely shuffled labels on the UMAP). In this case, I think it's safe to trust curators/submitters because the data format that is being used is often AnnData, which links AnnData.X and AnnData.obs when slicing, so most operations when curating the dataset won't break the pairing.
> In our case, if the cell identifiers are stored in the obs dataframe, and those identifiers are rewritten or shuffled, then it seems to fall into the same category of "we just can't tell with automatic validation". (edited)

@jychein

> [@bruce](https://czi-sci.slack.com/team/U46KYNDMJ) I was wondering the exact same thing after I wrote my comment. Looks like I was wrong, the validator does check for an unique index in obs. I just double checked with a redundant cell ID in a sample h5ad file, and it did not pass validation:
> ```
> % cellxgene-schema validate ~/Downloads/redundant_obs.h5ad 
> Loading dependencies
> Loading validator modules
> Starting validation...
> /Users/jychien/miniconda3/envs/validate_3.0.0/lib/python3.9/site-packages/anndata/_core/anndata.py:1828: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
>   utils.warn_names_duplicates("obs")
> WARNING: Validation of raw layer was not performed due to current errors, try again after fixing current errors.
> ERROR: Column 'index' in dataframe 'obs' is not unique.
> Validation complete in 0:00:01.214571 with status is_valid=False
> ```

@bkmartinjr 

> and that error came from AnnData, so I'm clearly wrong (above) when I said it did not care.
> EDIT - wait, that is a warning from AnnDAta.  I'm not sure who tagged it as not valid.  Maybe us.  Either way, very good to know. (edited) 

@jahilton

> Knowing that the obs index in a given dataset MUST be unique, why not have Census cell ID be a concatenation of the value in the obs.index + dataset ID?

@atarashansky 

> What if in a revision some cells get filtered out and some cells are added? if obs.index is just an integer range, then the IDs are no longer consistent

@bkmartinjr 

> the issue with using obs.index is that we don't make guarantees beyond "unique".  What happens if it changes?  We would need to change the guarantee to be stronger eg.,  will be unique and unchanged across all revisions of this dataset.
> I think this is more or less the same as having our curation process just assign a new column:  CZI_global_id  (with the added benefit of controlling type/id space, etc).   We could be hip and call it a cell accession number 

@jahilton 

> There is no guarantee that each observation will be ‘named’ the same through revisions - so we can’t make that claim
> Always possible that some revision changes the index values, etc.
> But it’s a pretty safe bet. And we do highly encourage the barcodes to not be dropped so we prevent the arbitrary integer ranges. so I don’t see any more reliable option 
> 
> > our curation process just assign a new column
> 
> If index values do change through a revision, how are curators supposed to validate & correct this in order to maintain these ids/accessions? That doesn’t seem feasible, or even possible, to me

@atarashansky 

> Upon initial submission, whatever the index values are at the time can be frozen in the CZ_global_id column of the obs metadata. If the index values change later, that's okay since we still have the original accessors in CZ_global_id. Upon adding new cells during a revision, their indices will be frozen in CZ_global_id.

@bkmartinjr 

> If your revisions always proceed from the same original source (i.e., mutate original), it is easy to preserve a pre-existing column. I'm guessing that is not the case, and you get entirely new H5ADs from the author?

@jahilton 

> > I’m guessing that is not the case, and you get entirely new H5ADs from the author?
>
> Correct, this happens

@bkmartinjr 

> The only thing I can think of as a fully generalized solution is to have a heuristic based on approximate equality.   Which would work most of the time with some human help (e.g, "ignore these genes")

@jahilton 

> Possibility that we discover that obs were actually scrambled relative to the matrix. And a revision correct that so the identifiers stay the same, but the expression values for each changes
> 
> > If the index values change later, that’s okay since we still have the original accessors in CZ_global_id
> But if the index values change, how are we supposed to know what each corresponding CZ_gloabl_id is?
>
>> maintaining it across all downstream revisions
> I still don’t see how this is going to be possible
> Example - Tabula sapiens is about to revise their datasets. This includes realignment, which will alter some gene expression values. How are curators supposed to confidently maintain a global-id from the current version to the updated version?

@atarashansky 

> Do authors have to remake the obs dataframe and all annotations therein from scratch before and after realignment?
> If not, then the realignment example shouldn't be an issue since czi-global-id would be a column in obs.
> And if the czi-global-id's are "C0", "C1", ..., "CN", then any new cells that were added after realignment would start at "CN+1"

@jahilton 

> 
> > Do authors have to remake the obs dataframe and all annotations therein from scratch before and after realignment?
> They get a whole new raw matrix fresh after alignment. So the whole process of normalization + add in metadata starts anew

@atarashansky 

> That seems like a good use case for "delete dataset_id and issue a new one".

@bkmartinjr  

> How are curators supposed to confidently maintain a global-id from the current version to the updated version
> In the limit, I get this is super hard.  But in the more common cases are there cheats we can use?  E.g., for 10X, can we use the barcode?
> I don't know enough to authoritatively answer.  Simply suggesting a "good enough" solution, plus the ability to burn a dataset_id, might be a path forward.

@jahilton 

>> That seems like a good use case for “delete dataset_id and issue a new one”.
> Deleting a dataset because someone updated their pipeline would break the strategy of making every version of the data available
> (as opposed to deleting a dataset because there were errors in the data or PII or something like that)
>> But in the more common cases are there cheats we can use? E.g., for 10X, can we use the barcode?
> Sure! But why not just allow the consumers to use these cheats?
> Because I don’t see anyway for us to make a guarantee on any cell ID persistence, So let’s just do something “good enough” (and incredibly low-hanging) & pass on the existing cell IDs

@jychien

> My concern would be that once people are accessing the Census, there is no way for them to associate the author specific metadata found in the original dataset. For example, there could be enrichment protocols or specific treatments that would affect the gene expression.
> I think providing an accession that ensures persistency across Census releases is too much. But just providing the original cell IDs found in the obs index would be very helpful. Having the column called something like author_cell_index or author_cell_id would not imply that it is an accession.

@bkmartinjr 

> We annotate every cell in the Census with the dataset_id that it was pulled from, so it is easy to get back to the dataset-level metadata.  But definitely no way to get back to the cell-specific metadata without solving same issues that make traceability a seeming non-starter....
> I guess a weak solution, but which might be commonly useful, would be to simply encode either the offset/iloc (cheap) or the obs.index (more expensive) in the census, documenting very well its limitations.  That would not provide traceability across census releases or dataset revisions (what Alec wants), but would provide access back to the author metadata.

**Comment by pablo-gar** [comment]
Summary:

- Unique and traceable cell IDs are important for myriad of user cases.
- We can easily guarantee uniqueness, but traceability is nearly impossible to guarantee.
- A strong motivating use case is being able to map back a cell from the Census to its equivalent cell in the source h5ad.

Moving forward.

- We enable mapping back cells from the Census to its original cell in the source h5ad by adding to the census an `obs` variable `source_index` that correspond to the obs.index of the original h5ad -- this doesn't ensure traceability between revision versions, but combining  `source_index` with `dataset_id` and the upcoming `dataset_version` a user can map cells between the Census and the source h5ad
- We _consider implementing_ a "good-enough" solution to traceable cell ids over revisions in dataset h5ad schema. Note: traceability can only be strongly recommended and not enforced, uniqueness should be enforced at the dataset level. We transfer all responsibility to curators to provide these IDs. Effectively we already have this type of ID with `donor_id`, we leave it to discretion of the curator to assign and create this ID (it could barcodes, curation-generated IDs, etc.). I will defer to @brianraymor on whether to _consider_ such implementation.

**Comment by pablo-gar** [comment]
On further discussion both points can (and likely should) be pass down to the dataset schema

**Comment by pablo-gar** [comment]
Per triage:

**Use case to fulfill** census cells must be able to be mapped to a cell in the source h5ad

**Requirements**

1. A row identifier is included in the dataset schema. Best encoding candidate, an integer ranging from 1 to number of cells in dataset under `adata.obs["source_cell_row"]`
2. The row identifier is included in the Census schema by drawing from the source h5ads.

**Allows**

1. Mapping a cell from the Census to the source h5ad.
2. Creating a unique cell id by concatenating `dataset_id`, `dataset_version_id` and `source_cell_row`.

**Comment by jahilton** [comment]
During the triage, there was no discussion/agreement of those specific requirements (actually, the discussion of those details was discouraged).
Why isn't the obs index being used for the row identifier instead of adding a new column?

**Comment by brianraymor** [comment]
@jahilton - I suggest the discussion about the **proposal** occur in https://github.com/chanzuckerberg/single-cell-curation/issues/522.

**Comment by pablo-gar** [comment]
This issue is now tracked at the dataset schema level https://github.com/chanzuckerberg/single-cell-curation/issues/522.
