### ISSUE TITLE
analytics: identify census builder H5AD download requests

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene-census#257]
See [**single-cell-census**](https://czi-sci.slack.com/archives/C048BN7K6U8/p1678737315058659). 

The census build downloads H5ADs from the portal.  This pollutes metrics.  It would be helpful if there was a way to identify the census (and WMG) builds, even if this is approximate and/or informal.

Ideas to explore:
- [x] identify by UA string or tag passed in HTTP headers
- [ ] identify by IP range

**Comment by pablo-gar** [comment]
This is blocked until guidance is offered from product team

cc @brianraymor

**Comment by pablo-gar** [comment]
@ainfeld should review and approve any proposals

**Comment by bkmartinjr** [comment]
TileDB support for setting headers landed in 2.18

Demo: https://gist.github.com/bekadavis9/be49edaef424f146334c31007ccf07a6

**Comment by bkmartinjr** [comment]
@danieljhegeman - closing this as implemented in #929   Please re-open if you disagree.  TY!
