### ISSUE TITLE
Computational consumers can perform modeling at scale of full Cell Census in a modern machine learning toolkit (PyTorch)

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#259]
Applying machine learning to the Cell Census is one of the primary paths to be used by computational biologists to make discoveries about the cell.

This path has been demonstrated by declared intents from our early users of the Cell Census (internal and external). This includes work from Ivana Jelic, Nick Sofroniew, Ana-Maria Istrate, and Jure Leskovec (in collaboration with Jonah Cool); all of whom intend to apply machine learning methods to the Cell Census to gain biological insights about the cell.

The current state-of-the-art machine learning framework is [PyTorch](https://pytorch.org/), and it should be the primary way to apply machine learning methods to the Cell Census data.

## Context

**Challenges**

- Data from the Cell Census needs to be converted by users to be used in a machine learning toolkit.
- At large scale, proper data structures need to be used for training in attainable time scales and computing power.
- Efficient data streaming is frequently required for large scale modeling, therefore users need to create custom hooks to allow TileDB-SOMA streaming capabilities to work with a machine learning toolkit.

## Stories

1. (Training) I am a computational biologist who would like to apply a **neural network** I developed to the **entire human data of the Cell Census**. If I can successfully apply the model I will be able to identify genome sites involved in cell type specification.
2. (Training) I am a computational biologist who is familiar with the **Variational Auto Encoder (VAE)** from SCVI and would like to apply it to **all of human data of the Cell Census.** This will allow me to integrate the data, generate embeddings, and perform the largest body-wise analysis of single-cell data to date. I cannot perform this with the canonical pipeline anndata-scvi because it is virtually impossible to achieve even with large computing. 
3. (Inference) I am a computational biologist who wants to train a classifier that utilizes single-cell data to infer ethnicity. My hypothesis is that single-cell data is enough to accurately predict ethnicity. Testing the hypothesis in and of itself is huge discovery milestone and importantly I can develop a tool to learn the donor's ethnicity from any single-cell dataset.

## Feature

A set of classes and methods that performantly connect all of the Cell Census data to PyTorch via TileDB-SOMA. 

## Product requirements

_Discovery work is still needed to refine the requirements below. Discovery work entails identifying areas of opportunity for increasing the efficiency in terms of time and memory of the requirements below in the context of TileDB-SOMA_

The entire Cell Census can be natively loaded and accessed for modeling on PyTorch through TileDB-SOMA:

1. A data representation ready for pytorch exists: A `torch.utils.data.Dataset` class for the Cell Census/TileDB-SOMA.
2. Data can be efficiently loaded in the data representation: A performant `torch.utils.data.DataLoader` for the `Dataset`. It must allow for efficient multi-core and low-latency data access.
3. Models can be applied to the data: A `pytorch_lightning.LightningModule` framework that utilizes the `Dataset` and the `Dataloader` (NEEDS MORE CLARIFICATION)

## Success of feature

The feature would be deemed successful if:

* A demonstration model can be trained in the full human data from the Cell Census. The deliverable on this is a notebook utilizing the feature to train a linear classifier for cell types.
* A more complex model can be trained on the full human data from the Cell Census. The deliverable on this is a notebook that trains a complex model (VAE from SCVI suggested).

## Anticipated resources needed

* One full time engineer performing initial discovery work and implementation. The engineer needs to work in coordination with TileDB-SOMA team to identify areas of overlap and coordinate the work with them.

**Comment by adamgayoso** [comment]
Hi @pablo-gar this would be super cool. Indeed we are pretty tied to anndata, but it should be possible to use our pytorch module and pytorch lightning module level of the code to train models, which is completely orthogonal to anndata and our user-facing model API.

**Comment by atolopko-czi** [comment]
For visibility, linking to the experimental code I've been working on this week: https://github.com/single-cell-data/TileDB-SOMA/blob/atol/torch-dataset-experimental/apis/python/src/tiledbsoma/io/pytorch.py.

Will follow-up next week w/thoughts about some requirements-level questions that we can work through, and decide if this is heading in the right direction.

**Comment by atolopko-czi** [comment]
With no PyTorch batching, `ExperimentDataPipe` returns training items that contain the obs `soma_joinid`, specified obs columns, and the X values for specified var columns. The X values can be returned either as sparse coo or dense Tensors.  Example:
```
[tensor(2491), 'a49d9109-1d0c-4b36-8139-19aa9a83428c', 'CL:0000789', tensor(indices=tensor([[    6,    22,    30,  ..., 32420, 32426, 32477],
                       [    0,     0,     0,  ...,     0,     0,     0]]),
       values=tensor([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
                       1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  4.,  1.,
                       1.,  1.,  1.,  1.,  1.,  1.,  1.,  3.,  1.,  1.,  1.,
...
]),
       size=(1, 33452), nnz=585, layout=torch.sparse_coo)]

On an EC2 m5.4xlarge, it retrieves the Lung HCA datasets (~500K cells) in ~6min using a single PyTorch DataLoader worker (i.e. unpartitioned). Not great, since we're intending to scale to much larger cell counts, up to the full corpus. The TileDB I/O only takes ~1.5mins, and the rest is data transformations, so hopefully a lot of room for improvements.

**Comment by brianraymor** [comment]
Confirming my understanding:
1. This epic will be complete in H1 per the schedule.
2. It's not DP related since Andrew is assigned. 

CC: @metakuni

**Comment by atolopko-czi** [comment]
> Confirming my understanding:
> 
> 1. This epic will be complete in H1 per the schedule.

Yes! MVP has been released and we already have one report of it having been successfully employed "out in the wild".

> 2. It's not DP related since Andrew is assigned.
> 
> CC: @metakuni

Yes, this is my understanding as well.

**Comment by atolopko-czi** [comment]
Moved final "unit testing" issue to next quarter's epic for PyTorch work. Closing this epic.
