### ISSUE TITLE
Add 30-day S3 lifecycle policy to cell-census data

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/cellxgene-census#271]
## Motivation

We have two requirements, which are in tension with each other:
1. The cell-census LTS (long-term support) builds need to be kept safe from accidental deletions.
2. Intermediate builds need to be fully deleted to avoid S3 billing costs. 

Since the bucket has versioning enabled, deleting intermediate builds with standard `aws s3 rm` semantics is not sufficient, as these are "logical" deletions, not physical deletions. But disabling bucket versioning puts LTS builds at risk.

To address both requirements, we can use S3's lifecycle policy to permanently delete any logically-deleted objects after a "safe" time period, say 30 days.

## Considerations

Logical deletions of 30-day old non-LTS builds are now performed during every census build (manually now, automatically in the near future).

## Definition of Done

- After 30 days, any logically-deleted S3 objects are _automatically_ physically deleted such that the deleted data no longer incurs an AWS cost.
- Any logically-deleted S3 objects can be recovered within 30 days of logical deletion.
- Any logically-deleted S3 objects belonging to a LTS build is detected prior to 30 days.

## Tasks
One of:
- [x] Add an S3 lifecycle management policy for `s3://cellxgene-data-public/cell-census` (note the bucket prefix) to https://github.com/chanzuckerberg/single-cell-infra/blob/main/terraform/envs/prod/soma/main.tf#L24, which physically deletes any logically deleted data after 30 days.
- [ ]  The build process (either manual or automated) verifies that all LTS builds in release.json are accessible on S3.  It should send an alert to the slack #single-cell-census channel. The command to recover the data should be provided. This should help catch and recover from any accidental deletions during the 30 day safety period.

For deletion detection, see also https://d0.awsstatic.com/whitepapers/protecting-s3-against-object-deletion.pdf. Other design options:
* Monitor CloudTrail events to detect S3 deletions
* Add a DataDog synthetic to check for each new LTS build. This would _not_ rely upon release.json as the master source of LTS builds.

It may also be worth having LTS S3 build prefixes include an obvious term like `long-term-stable-`.  This may also allow "reaper" lifecycle policies from considering objects including this prefix.

**Comment by atolopko-czi** [comment]
Closing issue, all aspects are now addressed or planned as future work:
* The 2nd task, `The build process (either manual or automated) verifies that all LTS builds in release.json are accessible on S3.` is now addressed by [this code](https://github.com/chanzuckerberg/cellxgene-census/blob/c2691154b39d28c395f84845a70c312b3b7ee3e2/tools/cellxgene_census_builder/src/cellxgene_census_builder/release_manifest.py#L88) that runs on every Census build release. If any release in the release.json file does not exist on S3, then the build will fail. This does rely upon the release.json being the source of truth on extant LTS releases, but this seems reasonable.  
* The 2nd task also stipulates, `The command to recover the data should be provided`, but this is now tracked in a new, more comprehensive issue: https://github.com/chanzuckerberg/cellxgene-census/issues/356.

**Comment by atolopko-czi** [comment]
Re-opening, realizing that https://github.com/chanzuckerberg/single-cell-infra/pull/729 is not yet merged/applied.

**Comment by ebezzi** [comment]
Closing as the lifecycle has been correctly applied and verified.
