### ISSUE TITLE
Create one-pager with high level summary of the Cell Census data hosting strategy

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#300]
## Motivation

To support #279 and to provide a pre-brief document for the trust review we need to summarize the **what** and **why** we are currently doing for hosting the Cell Census TileDB-SOMA object.

## Definition of Done

A document summarizing:

- The technical requirements of the TileDB-SOMA object needed for public access to the Cell Census data.
- Our current solution.

## Supporting information

This is the Cell Census high-level product summary submitted to the Trust Review

https://docs.google.com/document/d/1htKUsIkmm0oS4Km7RiiJBF_zebSEkWpwoOtGI1nCZCE/edit

**Comment by atolopko-czi** [comment]
https://docs.google.com/document/d/1NW_0XByd7ZiNFMx-R5GQsc8oZZxkhkAPPjgi_QPGh-c/edit#

**Comment by pablo-gar** [comment]
Delivered to @JaeiiLee
