### ISSUE TITLE
Update mentions of Census in SOMA and TileDB-SOMA repos

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#318]
Where "Cell Census" is named, change it to "Census" if in the context of CZ CELLxGENE Discover. Otherwise, if no context is provided then change to full name "CZ CELLxGENE Discover Census" 

- [ ] Update `single-cell-data/TileDB-SOMA/README.md`  --> make sure to update "channel `#cell-census-users`." to `#cellxgene-census-users`
- [ ] Update `single-cell-data/SOMA/README.md`

**Comment by bkmartinjr** [comment]
> `#cell-census-users`

This channel does not exist. @pablo-gar - do you want the docs updated before this channel exists?

**Comment by bkmartinjr** [comment]
See:
* single-cell-data/TileDB-SOMA#1211
* single-cell-data/SOMA#156

**Comment by bkmartinjr** [comment]
@pablo-gar - all is resolved except for the slack channel name.  Awaiting your feedback on this, as it did not seem prudent to update the README to point at a non-existent channel.

**Comment by bkmartinjr** [comment]
See also single-cell-data/TileDB-SOMA#1213
