### ISSUE TITLE
TissueMapper ontology should match Dataset schema ontology version

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/cellxgene-census#355]
## Motivation

The builder's UBERON (tissue) ontology obtains the ontology file directly from the 3rd party source, but is always the latest version available. This may be ahead of the version referenced in the Dataset Schema version.  The ontology file should be obtained from the Dataset Schema's "latest" UBERON version listed in https://raw.githubusercontent.com/chanzuckerberg/single-cell-curation/main/cellxgene_schema_cli/cellxgene_schema/ontology_files/owl_info.yml.

## Definition of Done

TissueMapper uses the same uberon ontology owl file as is used by the validation tool for a given Dataset Schema major version

## Tasks

- [x] Change the link at https://github.com/chanzuckerberg/cellxgene-census/blob/main/tools/cellxgene_census_builder/src/cellxgene_census_builder/build_soma/tissue_mapper.py#L123 
- [x] Update Schema Upgrade Process doc

**Comment by pablo-gar** [comment]
@brianraymor @atolopko-czi since this tissue mapper is a copy of the tissue mapper in the portal we probably want to address this sequentially.

1. Update the tissue mapper in portal.
2. Copy updated mapper to this repo.

What is the tracking issue for the portal equivalent? I was trying to find but was out of luck.

**Comment by brianraymor** [comment]
I need to decide how to model these issues within an epic. I think it should be included in the discovery plan for ontology-only updates. 

@pablo-gar Didn't you open an earlier issue - [feat: Develop system to maintain Gene Expression's Tissue Mapper class in sync with pinned UBERON ontology of h5ad schema](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/3573)?

**Comment by pablo-gar** [comment]
I'll stay tune for the model, and yes I opened that ticket asking to create such model. I will add it as dependency here, thanks!

**Comment by atolopko-czi** [comment]
> What is the tracking issue for the portal equivalent? 

Alec added this [https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/4495](issue) yesterday, but I now see that may have duped your earlier [issue](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell-data-portal/3573)
