### ISSUE TITLE
Census build S3 deletion recovery

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/cellxgene-census#356]
## Motivation

If an LTS build release gets deleted by accident, it would be time-advantageous to have a script ready to enumerate deleted releases and undelete a given release.

## Definition of Done

A script or, minimally, a set of instructions (a playbook) to:
1. Enumerate deleted releases. Note that we can inspect all past versions of release.json, which can be used to infer what LTS releases _should_ exist.
2. Undelete a specific Census release in the versioned S3 bucket.
3. Restore a (potentially) deleted release.json

**Comment by pablo-gar** [comment]
Do we need to this any time soon, or should we do this _when needed_ i.e. when and it it actually happens?

**Comment by atolopko-czi** [comment]
> Do we need to this any time soon, or should we do this _when needed_ i.e. when and it it actually happens?

Well, if we delete a LTS accidentally, how long are we willing to wait for an engineer to figure out how to undelete it reliably? 😄 Practically, this shouldn't be too hard, but an ounce of prevent...  Suggest we timebox this issue's effort to a couple hours.

**Comment by brianraymor** [comment]
This will not be required once #242 is implemented. Closing per triage.
