### ISSUE TITLE
Access to all the existing fields with keys outside the schema

### ISSUE THREAD

**Issue by ubyndr** [chanzuckerberg/cellxgene-census#363]
## Description

Currently all data is [standardized](https://github.com/chanzuckerberg/single-cell-curation/tree/main/schema/3.0.0) to include raw counts and a common vocabulary for gene and cell metadata. There is too much information in the dataset that is being overlooked. Is it possible to allow users to display additional annotations that are not included in the schema?

## Context

We are working on adding new terms to [Cell Ontology](https://github.com/obophenotype/cell-ontology). Users make new term requests and our curators tries to validate the term request by checking multiple data sources. We use [CZ CELLxGENE](https://cellxgene.cziscience.com/) as one of our data sources. Gene and cell metadata annotations are sufficient in most cases, but we would like to explore the effect free text annotations.

## Impact

We would like to explore how free text annotations affect Cell Ontology hierarchy.

## Ideal behavior 

Give users the ability to explore schema annotation and/or free text annotations with a new parameter or a flag.

**Comment by brianraymor** [comment]
See also [[Discussion/investigation] New schema field "author contributed cell type label"](https://github.com/chanzuckerberg/single-cell-curation/issues/414).

**Comment by dosumis** [comment]
Suggestion:  These fields should be made available as JSON blobs on each cell under a single 'additional field' key.

**Comment by jahilton** [comment]
A BIG ➕ from curation use cases. Downloading just the cell metadata for a Dataset (schema & non-schema) would make it much more efficient to compare metadata across datasets to understand data overlap (for is_primary_data curation), compare barcodes in the index values against 10x lists to curate assay, review annotation of tissue/cell_type terms relative to author-contributed fields, etc.

I would also think this facilitates the main use cases for the upcoming [observation_joinid](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/4.0.0/schema.md#observation_joinid). A Census user wants to pull data/metadata via Census API and then join that with additional metadata in the Dataset.

**Comment by pablo-gar** [comment]
This workflow now possible with the addition of `observation_joinid` to `obs`. The current workflow is demonstrated here with two datasets.

Demonstration Code with two datasets https://colab.research.google.com/drive/1-qIZJnDcwOfygTxr4069s96-Js7LoB_p 

We need to make a decision as to whether this is sufficient to close the ticket.
