### ISSUE TITLE
Census Docker build fails

### ISSUE THREAD

**Issue by MatthiasBeyens** [chanzuckerberg/cellxgene-census#376]
## Describe the bug

I want to reproduce a local Census instance with private data. I'm following the steps of creating a new release (https://github.com/chanzuckerberg/cellxgene-census/tree/main/tools/cellxgene_census_builder). Nonetheless, I'm stuck at the point of building a Docker image. 

## To Reproduce

Working on `main` commit `281ffdf53cb1c68a4017fbe40100cef3f759ec05`

```
./cellxgene-census/tools/cellxgene_census_builder/
make image
```
Added console logging (include error) in [console.log](https://github.com/chanzuckerberg/cellxgene-census/files/11212457/console.log)

## Expected behavior

Successful docker image build :)

## Environment

- macOS Monterey
- Apple M1
* Software versions: 
    - Docker desktop 4.17.0 

## Additional context

Would it ever be possible to reproduce Census platform within my own environment (following the data schema's as suggested) from a utilities and platform perspective? For now I downloaded some h5ad's directly from the Census S3 to make sure I can reproduce the platform as such, independent of h5ad formatting. Much appreciated!

**Comment by pablo-gar** [comment]
Thanks for raising this @MatthiasBeyens. I will get back to you on this shortly.

**Comment by pablo-gar** [comment]
Hi @MatthiasBeyens apologies for the delay we have a few conversations internally about this and we have made the decision to not support the builder code for external use. However we are interested in learning about why you wish to build a Census of you own as we may be able to point you in the right direction to accomplish your goals.

For example we or our partners at TileDB may be able to offer you support to use [TileDB-SOMA](https://github.com/single-cell-data/TileDB-SOMA/tree/main) for your ends (which is what the Census utilizes)
