### ISSUE TITLE
Git tag format for API releases must identify API language

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/cellxgene-census#382]
## Motivation

The versioning git tags for Python and R APIs will evolve separately, using different version "namespaces". Currently we only have versions for Python and they appear as "vX.Y.Z" (semver). There is no way to differentiate this version tag for each language API. Note that the Census summary info will include these version numbers, so they must be identifiable programmatically.

## Definition of Done

- Version tags have a structure that identifies the API language it pertains to.
- The Python API build scripts (GHA job) is updated to work with the new version tag format.
- The Python API build instructions are updated

**Comment by pablo-gar** [comment]
Let's address this once R 1.0 is out

**Comment by pablo-gar** [comment]
We first need to make a decision on what kind of model we want to use, the  options are:

1. API versions and github release are in sync
2. All versions are independent of each other, APIs and github releases

**Comment by pablo-gar** [comment]
We decided to go with option 1 and this ticket is not longer required.
