### ISSUE TITLE
Move cellxgene-data-public to a separate AWS account

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/cellxgene-census#395]
The [trust review](https://czi.atlassian.net/wiki/spaces/SECENG/pages/2704408577/2023-04-20+Security+Engineering+Office+Hours+Census+Data+Hosting+Architecture) requested that we move the existing public bucket to a separate AWS account to limit the interactions and increase the alertness level.

**Comment by pablo-gar** [comment]
This is an outcome of the trust review as detailed here #279

**Comment by atolopko-czi** [comment]
@ebezzi wrote a [Trust Review doc](https://docs.google.com/document/d/10Tbf19iF8Xz0eIiTYwEYOA4K6uQ7kAeRlYXcAevd9io/) to work through the remaining considerations that need guidance from Trust before we can finalize the architectural decisions.

**Comment by pablo-gar** [comment]
Completed
