### ISSUE TITLE
Create new AWS account

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/cellxgene-census#396]
A new AWS account needs to be created. central-infra will have to provision that.

- [x] A name should be decided by the census team.
- [x] The new AWS account needs to have a poweruser role set up for developers.
- [x] A Terraform Enterprise workspace should be created and bound to a single-cell-infra directory so that we can create the new infrastructure using Terraform.

**Comment by maniarathi** [comment]
On 2023-04-20 @pablo-gar @atolopko-czi @ebezzi @maniarathi met to decide that the name for the new AWS account will be `single-cell-public`. 
@maniarathi has scheduled a meeting with Travis Fields (Core Infra EM) on 2023-04-24 to discuss setting up the new account.

**Comment by maniarathi** [comment]
Infra issue tracked here: https://czi-tech.atlassian.net/browse/CCIE-1387
