### ISSUE TITLE
Create aws-config-generation for the new account

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/cellxgene-census#397]
An `aws-config-generation` needs to be created/added to Okta so that single cell developers can access the new account using a new profile. central-infra will be responsible for that.

**Comment by maniarathi** [comment]
Infra issue tracked here: https://czi-tech.atlassian.net/browse/CCIE-1387

**Comment by ebezzi** [comment]
This is completed. Reimporting the aws config will add the new role.
