### ISSUE TITLE
[builder] schema performance tuning

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene-census#4]
The prototype census builder uses the default TileDB-SOMA schema, which is unlikely to provide optimal performance for our particular use case. We need to identify benchmarks, and then measure/tune capacity/tile size, layout, filters/compressors, etc.

Possibilities to explore:
* dense vs sparse dataframe
* dict filter for obs/var label columns
* precision reduction filter for `raw` (which are ints by value)
* setting allow_dups after creation, when available in TileDB
* hilbert layout for X[*]

**Comment by bkmartinjr** [comment]
A large portion of the physical materialization tuning is resolved by #28

**Comment by bkmartinjr** [comment]
Further status:
- precision reduction is not worthwhile for the raw counts X layers, as they are already precision reduced (being primarily integer values coded as floats - they compress very well)
- allow_dups is enabled/resolved

We should explore tweaking the filter pipelines, as it is likely that higher compression levels would be a win (within reason - currently at zstd level 5, experiment modestly, eg, in the range 5-10).

**Comment by bkmartinjr** [comment]
Allows dups was implemented in #219

**Comment by pablo-gar** [comment]
Is #88 a duplicate of this? @atolopko-czi if that's the case do you mind closing #88?

**Comment by brianraymor** [comment]
@pablo-gar to follow up with @bkmartinjr to see if it can be closed and/or refined.

**Comment by bkmartinjr** [comment]
This was discussed at the most recent Census team meeting.  @pablo-gar has the info and has an action to decide on near-term priorities.

**Comment by pablo-gar** [comment]
This is not a priority and based on the mixed results (both gains and regressions) from Bruce's explorations this no longer a priority and I don't see ourselves doing more work related to this
