### ISSUE TITLE
Analytics should use the new bucket

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/cellxgene-census#401]
Analytics will need to use the new bucket.

**Comment by atolopko-czi** [comment]
Maybe investigate whether S3 logs can be sent from the new account bucket to the existing private `cellxgene-data-public-logs` bucket, cross-account

**Comment by ebezzi** [comment]
Essentially a duplicate of https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/cellxgene-census/402. Closing.
