### ISSUE TITLE
Add IAM role to enable bucket reads from single-cell-prod (for analytics)

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/cellxgene-census#402]
Since analytics will need access to the bucket (and the related logs bucket) and Databricks lives in single-cell-prod, we will need a cross account IAM role that allows the logs bucket to be read from single-cell-prod. central-infra will have to help with the setup.

**Comment by maniarathi** [comment]
Infra issue tracked here: https://czi-tech.atlassian.net/browse/CCIE-1387

**Comment by ebezzi** [comment]
Pending [this PR](https://github.com/chanzuckerberg/shared-infra/pull/7804) for completion. Requires someone from infra to fix the hung check.
