### ISSUE TITLE
Re-render doc-site with latest documentation assets

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#410]
On Thursday Apr 27 the entire doc-site (both readthedocs and pkgdown) needs to be re-render to reflect all the latest changes to the the documentation assets.

**Comment by ebezzi** [comment]
@pablo-gar I am closing this ticket since it's past Apr 27. Docs can be generated on demand now so I think small, pre-1.0 changes can go in without creating additional tickets.
