### ISSUE TITLE
Use "stable" releases instead of "latest" for doc-site

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#411]
## Description

Currently the main page of doc-site uses the "main" branch from github and puts it in "https://cellxgene-census.readthedocs.io/en/latest/" at the doc-stie domains. 

## Definition of done

1. To tie github releases to the versions shown in the doc-site
2. Tp choose a stable release that will be the main page for the doc-site under "https://cellxgene-census.readthedocs.io/en/stable/"

**Comment by ebezzi** [comment]
Closing as we don't use readthedocs anymore. The current build system triggers a docsite build on tag/release, which matches this ticket requirements.
