### ISSUE TITLE
Remove Mac certificate fix

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/cellxgene-census#415]
Once TileDB-SOMA Python API incorporates the necessary fixes for the Mac certificate issue (see #414), the fix can be removed from the Census Python API.

**Comment by bkmartinjr** [comment]
@atolopko-czi - did this issue get filed against TiledB-SOMA?  I can't find an issue in that repo - it would be good to add a link so we can revert this work-around when it is fixed.

**Comment by atolopko-czi** [comment]
Empirically, it appears to be fixed, after removing the hack. Checking w/TileDB folks to confirm it's actually fixed (and that I'm not fooling myself).

**Comment by atolopko-czi** [comment]
John confirmed this was fixed in https://github.com/TileDB-Inc/TileDB-Py/releases/tag/0.22.0 (core 0.2.16.0) via  https://github.com/TileDB-Inc/TileDB/pull/4059.
