### ISSUE TITLE
Schema addresses all assays

### ISSUE THREAD

**Issue by jahilton** [chanzuckerberg/cellxgene-census#441]
## Description

The schema should address all assays in CELLxGENE, whether they are included in the Census or not

## Context

A user may see data in CELLxGENE but not in the Census and wonder why. The Census can address this by noting in the schema which assays are excluded and why. This is currently done for sci-Plex & Slide-seq & Slide-seqV2, but not others (eg 10x multiome, Visium)

**Comment by Yanay1** [comment]
+1

For example, this collection: https://cellxgene.cziscience.com/collections/8e880741-bf9a-4c8e-9227-934204631d2a

If I want to download all these datasets right now, I have to manually download over 100 files (if I want to keep the spatial data). Spatial data should be included in the API although even if it is not in the census.

**Comment by pablo-gar** [comment]
Addressed in #740
