### ISSUE TITLE
Update package release.json bootstrap URI once cloudfront changes land

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene-census#452]
Once chanzuckerberg/single-cell-infra#780 has landed (creating a permalink for the release.json bootstrap URL), update the python code to match.

CC: @mlin - at some point, you will want to do the same for R, but it does not need to be immediate as the old URI will continue to work for the time being.

**Comment by ebezzi** [comment]
Closing as completed.
