### ISSUE TITLE
Finalize conventions for recording LTS data releases

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#457]
## Motivation

We currently don't have a final system to tag and surface LTS data release in the `release.json` and the API respectively.

**Definitions**

Please see definition of data releases [here](https://github.com/chanzuckerberg/cellxgene-census/blob/main/docs/cellxgene_census_docsite_data_release_info.md#long-term-supported-lts-cell-census-releases).

Labels used by API in `open_soma(census_version = "")`:

- "stable" is the latest LTS data release
- "latest" is the current weekly release

**User stories**

1. I want to access the latest Census data release that contains datasets from as late as last week. 
2. I want to access the latest LTS Census data release. And I would want to know which specific version it is so that in the future I can get use this exact version to get consistent results.
3. I want to access a specific LTS Census data release for consistency.
4. I want to understand if, why, and which LTS Census releases have been removed. 

**Product requirements**

This system must:

- Be backwards compatible with current implementation
- Allow a future version of the API to identify all data releases available to `open_soma`.
- Allow a future version of the API to identify all LTS data releases available to `open_soma`
- The LTS release names surfaced to the user must be clear and indicate they are LTS, as well as their build dates.
- `open_soma` should provide clear messaging of what version is being opened (**already satisfied**).
- The default `census_version = "stable"` of `open_soma` must open the latest LTS data release.
- `census_version = "latest"` of `open_soma` must open the current weekly release.
- In the unlikely edge-case where an LTS is deleted:
   - The system must retire the data release and flag it as such.
   - They system must be able to record the reason for its removal.
   - The (aforementioned future) API must provide access to this reason/metadata
- The APIs must:
    - Allow to get the aliases of all LTS's
    - Provide clear information of the release being opened upon calling `open_soma` (already implemented)   - The API must provide an error with clear messaging if a user tries to open it via `open_soma`

## Proposed implementation

The following serves as a _guide_ for eng but final design is up to engineers

The `release.json` has the following conventions:

- A dynamic alias `"stable"` that points to the latest LTS data release (already implemented)
- A dynamic alias `"latest"` that points to the current weekly release (already implemented)
- Each LTS data release must be named with the convention `"LTS-[YY.MM]"` (new)
- Each release must have a key `is_LTS` which must be True if the release is an LTS, False otherwise (new)

Latest example `release.json` as of 2023-08-23:

```json
{
  "stable": "2023-07-25",
  "latest": "2023-08-22",
  "2023-05-15": {
    "release_date": null,
    "release_build": "2023-05-15",
    "soma": {
      "uri": "s3://cellxgene-data-public/cell-census/2023-05-15/soma/",
      "relative_uri": "/cell-census/2023-05-15/soma/",
      "s3_region": "us-west-2"
    },
    "h5ads": {
      "uri": "s3://cellxgene-data-public/cell-census/2023-05-15/h5ads/",
      "relative_uri": "/cell-census/2023-05-15/h5ads/",
      "s3_region": "us-west-2"
    },
    "do_not_delete": true
  },
  "2023-07-17": {
    "release_date": null,
    "release_build": "2023-07-17",
    "soma": {
      "uri": "s3://cellxgene-data-public/cell-census/2023-07-17/soma/",
      "relative_uri": "/cell-census/2023-07-17/soma/",
      "s3_region": "us-west-2"
    },
    "h5ads": {
      "uri": "s3://cellxgene-data-public/cell-census/2023-07-17/h5ads/",
      "relative_uri": "/cell-census/2023-07-17/h5ads/",
      "s3_region": "us-west-2"
    }
  },
  "2023-07-24": {
    "release_date": null,
    "release_build": "2023-07-24",
    "soma": {
      "uri": "s3://cellxgene-data-public/cell-census/2023-07-24/soma/",
      "relative_uri": "/cell-census/2023-07-24/soma/",
      "s3_region": "us-west-2"
    },
    "h5ads": {
      "uri": "s3://cellxgene-data-public/cell-census/2023-07-24/h5ads/",
      "relative_uri": "/cell-census/2023-07-24/h5ads/",
      "s3_region": "us-west-2"
    }
  },
  "2023-07-25": {
    "release_date": null,
    "release_build": "2023-07-25",
    "soma": {
      "uri": "s3://cellxgene-data-public/cell-census/2023-07-25/soma/",
      "relative_uri": "/cell-census/2023-07-25/soma/",
      "s3_region": "us-west-2"
    },
    "h5ads": {
      "uri": "s3://cellxgene-data-public/cell-census/2023-07-25/h5ads/",
      "relative_uri": "/cell-census/2023-07-25/h5ads/",
      "s3_region": "us-west-2"
    },
    "do_not_delete": true
  },
  "2023-08-01": {
    "release_date": null,
    "release_build": "2023-08-01",
    "soma": {
      "uri": "s3://cellxgene-data-public/cell-census/2023-08-01/soma/",
      "relative_uri": "/cell-census/2023-08-01/soma/",
      "s3_region": "us-west-2"
    },
    "h5ads": {
      "uri": "s3://cellxgene-data-public/cell-census/2023-08-01/h5ads/",
      "relative_uri": "/cell-census/2023-08-01/h5ads/",
      "s3_region": "us-west-2"
    },
    "do_not_delete": false
  },
  "2023-08-08": {
    "release_date": null,
    "release_build": "2023-08-08",
    "soma": {
      "uri": "s3://cellxgene-data-public/cell-census/2023-08-08/soma/",
      "relative_uri": "/cell-census/2023-08-08/soma/",
      "s3_region": "us-west-2"
    },
    "h5ads": {
      "uri": "s3://cellxgene-data-public/cell-census/2023-08-08/h5ads/",
      "relative_uri": "/cell-census/2023-08-08/h5ads/",
      "s3_region": "us-west-2"
    },
    "do_not_delete": false
  },
  "2023-08-14": {
    "release_date": null,
    "release_build": "2023-08-14",
    "soma": {
      "uri": "s3://cellxgene-data-public/cell-census/2023-08-14/soma/",
      "relative_uri": "/cell-census/2023-08-14/soma/",
      "s3_region": "us-west-2"
    },
    "h5ads": {
      "uri": "s3://cellxgene-data-public/cell-census/2023-08-14/h5ads/",
      "relative_uri": "/cell-census/2023-08-14/h5ads/",
      "s3_region": "us-west-2"
    },
    "do_not_delete": false
  },
  "2023-08-22": {
    "release_date": null,
    "release_build": "2023-08-22",
    "soma": {
      "uri": "s3://cellxgene-data-public/cell-census/2023-08-22/soma/",
      "relative_uri": "/cell-census/2023-08-22/soma/",
      "s3_region": "us-west-2"
    },
    "h5ads": {
      "uri": "s3://cellxgene-data-public/cell-census/2023-08-22/h5ads/",
      "relative_uri": "/cell-census/2023-08-22/h5ads/",
      "s3_region": "us-west-2"
    },
    "do_not_delete": false
  }
}
```

**Comment by atolopko-czi** [comment]
Another requirement to consider: "Ability to retract an LTS, and make this apparent to the user".

We should also decide if we're committed to the current release.json structure (for now) or whether we can evolve it when addressing this, since there may ways to improve the file structure. Spitballing:
```
{
  weekly: [
    { "2022-10-08": "2022-10-08" },
    { "2022-09-08": "2022-09-08" }
  ]
  stable: [
    { "LTS-2022-10": { build: "2022-10-08", retracted: null },
    { "LTS-2022-09": { build: "2022-09-08", retracted: "2022-10-07" }
  ]
  builds: {
    "2022-11-08": { "soma": ..., "h5ads": ... },
    "2022-10-08": { "soma": ..., "h5ads": ... },
    "2022-09-08": { "soma": ..., "h5ads": ... },
  }
}
```
This separates the "raw" builds from what they mean (weekly, stable, etc.). Still supports aliases. Supports LTS retraction. Supports explicit ordering of weekly/stable for display purposes (via use of json arrays).  Plenty of other ways to structure this, of course, so let's iterate in a meeting perhaps.

**Comment by atolopko-czi** [comment]
Note to self: above release.json is no longer that latest.
