### ISSUE TITLE
Could not find module 'tiledbsoma.dll' (or one of its dependencies). Try using the full path with constructor syntax

### ISSUE THREAD

**Issue by daweibushen** [chanzuckerberg/cellxgene-census#470]
## Describe the bug
when I install by : pip install -U cellxgene-census, get error
Could not find module 'tiledbsoma.dll' (or one of its dependencies). Try using the full path with constructor syntax
Collecting cellxgene-census
  Downloading cellxgene_census-1.0.0-py3-none-any.whl (11 kB)
Collecting s3fs
  Downloading s3fs-2023.5.0-py3-none-any.whl (28 kB)
Requirement already satisfied: certifi in d:\anaconda\lib\site-packages (from cellxgene-census) (2022.12.7)
Collecting tiledb>=0.21.3
  Downloading tiledb-0.21.3-cp310-cp310-win_amd64.whl (5.2 MB)
     ---------------------------------------- 5.2/5.2 MB 3.4 MB/s eta 0:00:00
Requirement already satisfied: numpy<1.24,>=1.21 in d:\anaconda\lib\site-packages (from cellxgene-census) (1.23.5)
Requirement already satisfied: requests in d:\anaconda\lib\site-packages (from cellxgene-census) (2.28.1)
Requirement already satisfied: typing-extensions in d:\anaconda\lib\site-packages (from cellxgene-census) (4.4.0)
Requirement already satisfied: anndata in d:\anaconda\lib\site-packages (from cellxgene-census) (0.9.1)
Collecting tiledbsoma==1.2.2
  Downloading tiledbsoma-1.2.2.tar.gz (146 kB)
     ---------------------------------------- 146.5/146.5 kB ? eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: scipy in d:\anaconda\lib\site-packages (from cellxgene-census) (1.10.0)
Requirement already satisfied: scanpy>=1.9.2 in d:\anaconda\lib\site-packages (from tiledbsoma==1.2.2->cellxgene-census) (1.9.3)
Requirement already satisfied: pyarrow>=9.0.0 in d:\anaconda\lib\site-packages (from tiledbsoma==1.2.2->cellxgene-census) (12.0.0)
Collecting attrs>=22.2
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Requirement already satisfied: numba==0.56.4 in d:\anaconda\lib\site-packages (from tiledbsoma==1.2.2->cellxgene-census) (0.56.4)
Requirement already satisfied: pandas in d:\anaconda\lib\site-packages (from tiledbsoma==1.2.2->cellxgene-census) (1.5.3)
Collecting somacore==1.0.1
  Downloading somacore-1.0.1-py3-none-any.whl (32 kB)
Requirement already satisfied: packaging in d:\anaconda\lib\site-packages (from tiledb>=0.21.3->cellxgene-census) (22.0)
Requirement already satisfied: setuptools in d:\anaconda\lib\site-packages (from numba==0.56.4->tiledbsoma==1.2.2->cellxgene-census) (65.6.3)
Requirement already satisfied: llvmlite<0.40,>=0.39.0dev0 in d:\anaconda\lib\site-packages (from numba==0.56.4->tiledbsoma==1.2.2->cellxgene-census) (0.39.1)
Requirement already satisfied: natsort in d:\anaconda\lib\site-packages (from anndata->cellxgene-census) (8.3.1)
Requirement already satisfied: h5py>=3 in d:\anaconda\lib\site-packages (from anndata->cellxgene-census) (3.7.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\anaconda\lib\site-packages (from requests->cellxgene-census) (1.26.14)
Requirement already satisfied: charset-normalizer<3,>=2 in d:\anaconda\lib\site-packages (from requests->cellxgene-census) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda\lib\site-packages (from requests->cellxgene-census) (3.4)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in d:\anaconda\lib\site-packages (from s3fs->cellxgene-census) (3.8.4)
Collecting fsspec==2023.5.0
  Downloading fsspec-2023.5.0-py3-none-any.whl (160 kB)
     ------------------------------------- 160.1/160.1 kB 10.0 MB/s eta 0:00:00
Collecting aiobotocore~=2.5.0
  Downloading aiobotocore-2.5.0-py3-none-any.whl (72 kB)
     ---------------------------------------- 72.7/72.7 kB 3.9 MB/s eta 0:00:00
Collecting aioitertools>=0.5.1
  Downloading aioitertools-0.11.0-py3-none-any.whl (23 kB)
Requirement already satisfied: wrapt>=1.10.10 in d:\anaconda\lib\site-packages (from aiobotocore~=2.5.0->s3fs->cellxgene-census) (1.14.1)
Collecting botocore<1.29.77,>=1.29.76
  Downloading botocore-1.29.76-py3-none-any.whl (10.4 MB)
     ---------------------------------------- 10.4/10.4 MB 7.4 MB/s eta 0:00:00
Requirement already satisfied: yarl<2.0,>=1.0 in d:\anaconda\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs->cellxgene-census) (1.9.2)
Requirement already satisfied: aiosignal>=1.1.2 in d:\anaconda\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs->cellxgene-census) (1.3.1)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in d:\anaconda\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs->cellxgene-census) (4.0.2)
Requirement already satisfied: multidict<7.0,>=4.5 in d:\anaconda\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs->cellxgene-census) (6.0.4)
Requirement already satisfied: frozenlist>=1.1.1 in d:\anaconda\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs->cellxgene-census) (1.3.3)
Requirement already satisfied: pytz>=2020.1 in d:\anaconda\lib\site-packages (from pandas->tiledbsoma==1.2.2->cellxgene-census) (2022.7)
Requirement already satisfied: python-dateutil>=2.8.1 in d:\anaconda\lib\site-packages (from pandas->tiledbsoma==1.2.2->cellxgene-census) (2.8.2)
Requirement already satisfied: session-info in d:\anaconda\lib\site-packages (from scanpy>=1.9.2->tiledbsoma==1.2.2->cellxgene-census) (1.0.0)
Requirement already satisfied: seaborn in d:\anaconda\lib\site-packages (from scanpy>=1.9.2->tiledbsoma==1.2.2->cellxgene-census) (0.12.2)
Requirement already satisfied: joblib in d:\anaconda\lib\site-packages (from scanpy>=1.9.2->tiledbsoma==1.2.2->cellxgene-census) (1.1.1)
Requirement already satisfied: tqdm in d:\anaconda\lib\site-packages (from scanpy>=1.9.2->tiledbsoma==1.2.2->cellxgene-census) (4.64.1)
Requirement already satisfied: networkx>=2.3 in d:\anaconda\lib\site-packages (from scanpy>=1.9.2->tiledbsoma==1.2.2->cellxgene-census) (2.8.4)
Requirement already satisfied: scikit-learn>=0.22 in d:\anaconda\lib\site-packages (from scanpy>=1.9.2->tiledbsoma==1.2.2->cellxgene-census) (1.2.1)
Requirement already satisfied: statsmodels>=0.10.0rc2 in d:\anaconda\lib\site-packages (from scanpy>=1.9.2->tiledbsoma==1.2.2->cellxgene-census) (0.13.5)
Requirement already satisfied: patsy in d:\anaconda\lib\site-packages (from scanpy>=1.9.2->tiledbsoma==1.2.2->cellxgene-census) (0.5.3)
Requirement already satisfied: umap-learn>=0.3.10 in d:\anaconda\lib\site-packages (from scanpy>=1.9.2->tiledbsoma==1.2.2->cellxgene-census) (0.5.3)
Requirement already satisfied: matplotlib>=3.4 in d:\anaconda\lib\site-packages (from scanpy>=1.9.2->tiledbsoma==1.2.2->cellxgene-census) (3.7.0)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in d:\anaconda\lib\site-packages (from botocore<1.29.77,>=1.29.76->aiobotocore~=2.5.0->s3fs->cellxgene-census) (0.10.0)
Requirement already satisfied: pyparsing>=2.3.1 in d:\anaconda\lib\site-packages (from matplotlib>=3.4->scanpy>=1.9.2->tiledbsoma==1.2.2->cellxgene-census) (3.0.9)
Requirement already satisfied: cycler>=0.10 in d:\anaconda\lib\site-packages (from matplotlib>=3.4->scanpy>=1.9.2->tiledbsoma==1.2.2->cellxgene-census) (0.11.0)
Requirement already satisfied: pillow>=6.2.0 in d:\anaconda\lib\site-packages (from matplotlib>=3.4->scanpy>=1.9.2->tiledbsoma==1.2.2->cellxgene-census) (9.4.0)
Requirement already satisfied: fonttools>=4.22.0 in d:\anaconda\lib\site-packages (from matplotlib>=3.4->scanpy>=1.9.2->tiledbsoma==1.2.2->cellxgene-census) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in d:\anaconda\lib\site-packages (from matplotlib>=3.4->scanpy>=1.9.2->tiledbsoma==1.2.2->cellxgene-census) (1.4.4)
Requirement already satisfied: contourpy>=1.0.1 in d:\anaconda\lib\site-packages (from matplotlib>=3.4->scanpy>=1.9.2->tiledbsoma==1.2.2->cellxgene-census) (1.0.5)
Requirement already satisfied: six>=1.5 in d:\anaconda\lib\site-packages (from python-dateutil>=2.8.1->pandas->tiledbsoma==1.2.2->cellxgene-census) (1.16.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in d:\anaconda\lib\site-packages (from scikit-learn>=0.22->scanpy>=1.9.2->tiledbsoma==1.2.2->cellxgene-census) (2.2.0)
Requirement already satisfied: pynndescent>=0.5 in d:\anaconda\lib\site-packages (from umap-learn>=0.3.10->scanpy>=1.9.2->tiledbsoma==1.2.2->cellxgene-census) (0.5.10)
Requirement already satisfied: stdlib-list in d:\anaconda\lib\site-packages (from session-info->scanpy>=1.9.2->tiledbsoma==1.2.2->cellxgene-census) (0.8.0)
Requirement already satisfied: colorama in d:\anaconda\lib\site-packages (from tqdm->scanpy>=1.9.2->tiledbsoma==1.2.2->cellxgene-census) (0.4.6)
Building wheels for collected packages: tiledbsoma
  Building wheel for tiledbsoma (pyproject.toml): started
  Building wheel for tiledbsoma (pyproject.toml): finished with status 'error'
Failed to build tiledbsoma
Note: you may need to restart the kernel to use updated packages.
  error: subprocess-exited-with-error
  
  Building wheel for tiledbsoma (pyproject.toml) did not run successfully.
  exit code: 1
  
  [5 lines of output]
  running bdist_wheel
  Checking: C:\Users\dawei bushen\AppData\Local\Temp\pip-install-cnpsyu3e\tiledbsoma_e2881eba42714a998e29c98e09ab98a5\dist_links\dist\lib\tiledbsoma.dll exists: False
  Checking: C:\Users\dawei bushen\AppData\Local\Temp\pip-install-cnpsyu3e\tiledbsoma_e2881eba42714a998e29c98e09ab98a5\dist_links\dist\bin\tiledbsoma.dll exists: False
  Could not find module 'tiledbsoma.dll' (or one of its dependencies). Try using the full path with constructor syntax.
  error: [WinError 2] 系统找不到指定的文件。
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tiledbsoma
ERROR: Could not build wheels for tiledbsoma, which is required to install pyproject.toml-based projects

## To Reproduce

pip install -U cellxgene-census

## Environment

Provide a description of your system and the software versions.

Python 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]
Windows-10-10.0.19045-SP0

**Comment by pablo-gar** [comment]
Hello!

Thanks for you interest on Census, unfortunately `tiledbsoma` which is a central dependency of `cellxgene-census` is not supported on Windows. A potential and completely untested option to consider is [WSL](https://learn.microsoft.com/en-us/windows/wsl/install).

If you have access to a Linux/Mac machine I would recommend that. Alternatively you could use the Census for light-weight usage via google colab. For example:

https://colab.research.google.com/drive/1ytioSg1XtBg5vJTlPxiYgjoJC4tBvZkb?usp=sharing#scrollTo=hp6h0_lZJyEv

**Comment by daweibushen** [comment]
thank you very much for reply，thats really pity，cellxgene-census is so good for single cell analysis，but i only have windows system。
