### ISSUE TITLE
Test WSL support 

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/cellxgene-census#474]
## Description

Currently tiledbsoma is supported only on MacOS and Linux, leaving Windows users unable to access the census. We need to test if tiledbsoma works with WSL (Windows Linux Subsystem).

## Context

We have evidence that users are interested in Windows support:
1. Pypi download stats showed some Windows downloads
2. https://github.com/chanzuckerberg/cellxgene-census/issues/470

## Impact

This will enable more users to access the census, so it is medium-high impact. Need to assess whether this works out of the box or needs additional tweaks. Potentially ask TileDB.

## Alternatives you've considered

If no native Windows support is available, WSL is the only option.

## Ideal behavior 

Census working on Windows via WSL.

**Comment by pablo-gar** [comment]
I don't see ourselves supporting Windows anytime soon. I'm going to close this for now.
