### ISSUE TITLE
[r] Replicate open_soma() user warnings in R

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/cellxgene-census#482]
See Python changes to add have open_soma() default to `stable` and added user warnings: #435

**Comment by ebezzi** [comment]
Make sure that the vignette api/r/cellxgene.census/vignettes/comp_bio_census_info.Rmd is also updated to reflect this change. At line 31, 

>The `cellxgene.census` R package  contains a convenient `open_soma()` API to open any version of the Census (the latest by default).

should be (roughly)

> The `cellxgene.census` R package  contains a convenient `open_soma()` API to open any version of the Census (the stable by default).

**Comment by mlin** [comment]
I'll take care of this once the `stable` key exists in the `release.json`, if that's alright with everyone

**Comment by pablo-gar** [comment]
That sounds good!
