### ISSUE TITLE
Add a documentation section for Apple M1/M2 users

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/cellxgene-census#487]
## Motivation

Users with a MacBook using M1/M2 chips are encountering issues with installing tiledbsoma. We should have a documentation section for it.

## Definition of Done

A documentation section is added that explains:
- What is the current state of support for M1/M2 chips
- What installation options work

**Comment by bkmartinjr** [comment]
The FAQ and Quick start/installation should  also highlight common supported/unsupported platforms,.
