### ISSUE TITLE
Benchmark PyTorch DataLoader

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/cellxgene-census#514]
Run benchmarks to establish the baseline performance of the PyTorch DataLoader.  The purpose is to ensure that performance is not significantly slower than an equivalent ExperimentAxisQuery data loading. This effectively tests that the iteration and Tensor transformation logic is not incurring significant performance degradation.

* Varying obs, ~var~ sizes. 
* Dense vs Sparse tensors
* Batch size
* SOMA buffer bytes config option
* Single workers vs multiple workers
* Eager vs Lazy fetch
* ~Tensor precision: `torch.set_float32_matmul_precision('medium' | 'high')` [docs](https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision)~

**Comment by pablo-gar** [comment]
@atolopko-czi I'm marking this as a P0 since it is relevant to our work related to SCVI

**Comment by atolopko-czi** [comment]
Note (as discussed), SCVI-specific benchmarking is tracked by https://github.com/chanzuckerberg/cellxgene-census/issues/530. This is just "raw" Census PyTorch DataLoader benchmarking, w/o any model training component.

**Comment by atolopko-czi** [comment]
Profiling code and results will be stored in the repo: https://github.com/atolopko-czi/census-scvi-bench

**Comment by atolopko-czi** [comment]
Initial benchmarking results have been run: [analysis](https://github.com/atolopko-czi/census-pytorch-bench/blob/main/profiling-analysis.txt)
