### ISSUE TITLE
Integrate schema gated dataset fetch with Census Builder

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/cellxgene-census#518]

**Comment by pablo-gar** [comment]
Dup of #89 maybe?

**Comment by brianraymor** [comment]
@pablo-gar - it's not precisely a dup, but it's definitely related.

#89 is about the census builder making copies now that the Discover API supports permanent dataset version urls. And depending on where we land with the deletion policy, there may be some advantages for census to keep making copies. 

This issue is about **how** the census builder requests the datasets. This issue allows census builder to keep requesting schema 3 versions until it's ready for schema 4 versions.
