### ISSUE TITLE
Add nightly test with expanded set of unit test markers and platform matrix

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene-census#523]
Motivated by #521, we should add a _nightly_ GHA workflow with an expanded set of test markers and platform matrix.

Suggested markers beyond the default:
* --experimental --live-corpus
* on Py 3.8+ (pytorch-related tests not yet supported on 3.7)

Don't add --expensive mark, as that is known to require more resources than can succeed on GHA runners.

CC: @atolopko-czi

**Comment by pablo-gar** [comment]
Good suggestion. I'm marking as P1 as the original issue does not replicate on GA. Please feel free to change if you disagree since this seems to be an issue that applies to developers only (i.e. census engineers).

**Comment by atolopko-czi** [comment]
Resolved for now by running experimental tests on all supported GHA job matrix options, which means all except Python 3.7. If unit test run time is too long, we will first address by attempting to reduce test times. If we cannot, then the full test matrix will be moved to a nightly build, per this issue.
