### ISSUE TITLE
Builder must implement `X["normalized"]`

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#562]
Implements #290 
Add `census['census_dat'][organism].ms["RNA"].X["normalized"]` to Census data.

**Comment by bkmartinjr** [comment]
@pablo-gar - please add a specification of what this layer contains.  How does it differ from #290?

**Comment by pablo-gar** [comment]
Same and one #290 is a ticket for the schema text. This is the ticket for the corresponding builder changes.

**Comment by bkmartinjr** [comment]
OK. The change of name confused me :-)
