### ISSUE TITLE
Modify the Python API to support mirrors and relative URIs

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/cellxgene-census#586]
The Python API should support mirrors and relative URIs in the release.json file.

Rough steps:
1. Add a `mirror` parameter to `get_census_version_description`
2. In `get_census_version_description`, add a call to `/v1/mirrors.json` to retrieve the mirror list, including the default one.
3. In `get_census_version_description`, instead of the `uri` field, use `relative_uri` (to be introduced in #586) and create an absolute URI using the mirror's bucket name. If `mirror` is None, use the default mirror.
4. Introduce a `mirror` parameter in `open_soma` that gets passed to `get_census_version_description`. This parameter is user-facing, so it should be well documented

Since for the time being we will only support one mirror, I don't think it's necessary to add anything else - e.g. an API for getting the mirrors list. That can be done later. 

[Release timeline](https://docs.google.com/document/d/1MS-hrkg7VWKlHIk5Ow4CH7Sg0UzGle2sD_WB0kSgbiE/edit)

**Comment by pablo-gar** [comment]
Completed at #522
