### ISSUE TITLE
Investigate census builder failures

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/cellxgene-census#595]
The failure [previously reported here](https://github.com/chanzuckerberg/cellxgene-census/issues/311#issuecomment-1558052889) showed up a few more times. We have empirical evidence that this failure can happen even on subsequent runs, and it generally goes away the day after. This means that retries won't help, and there might be underlying issues that a retry could mask.

We'll need further investigation. Here are a couple of options, assuming that the failure is on the client side:
1. Increase logging. The stack trace doesn't clearly show where the error happens in the code, and which dataset is causing the failure.
2. Save the dmesg logs from the builder machine.
3. Investigate if there are settings for the used library that could help.
4. Decrease/tune the parallelism

Another possible theory is that the failure is on the server/API side. Since the requests are served by Cloudfront, we could:
1. Turn on Cloudfront logging and be ready to correlate the failure when it happens
2. Research if serving large files on S3 via Cloudfront is actually a recommended practice.

**Comment by pablo-gar** [comment]
Please implement this #311 and see if issue persists

**Comment by pablo-gar** [comment]
Likely resolved by work included in #716, we will keep monitoring and will re-open if necessary.
