### ISSUE TITLE
Add `dataset_version_id`  to schema

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene-census#6]
EDIT by @pablo-gar This is schema issue its corresponding builder ticket is captured elsewhere #548

Currently the schema does not store the stable immutable `dataset_artifact_id`. It was not included due to the following reasons:

1. We need to use a [deprecated non-public API ]([https://api.cellxgene.cziscience.com/dp/ui/#/datasets/backend.portal.api.app.v1.dataset.get_dataset_assets](https://www.google.com/url?q=https://api.cellxgene.cziscience.com/dp/ui/%23/datasets/backend.portal.api.app.v1.dataset.get_dataset_assets&sa=D&source=docs&ust=1667848968076301&usg=AOvVaw0apsILFh0fbT0ykwsAKTKs).)to obtain it.
2. We will use a different id `dataset_version_id` in a few months which will replace `dataset_artifact_id`
3. At this moment the Cell Census MVP prioritizes external end-user capabilities. This ID is mainly for internal traceability. 

@atolopko-czi says

> By end of quarter [Q4 2022], we'll have another ID we might consider using instead: dataset_version_id. So perhaps a future census schema version deals with provenance when we're better prepared to support it internally.

~If the development of this new `dataset_version_id` does not finish when promised we will revisit alternatives such as `dataset_artifact_id`~

A new Discover API `/v1/datasets/` endpoint will be added by https://github.com/chanzuckerberg/single-cell-data-portal/issues/4324, which can be used to implement this issue. The endpoint will expose the latest `dataset_version_id` for all datasets and will provide the direct (not pre-signed) S3 URL that can be used be to download the H5AD file.

## Schema addition

Under header **Census table of CELLxGENE Discover datasets – `census_obj["census_info"]["datasets"]` – `SOMADataFrame``**

<table>
<thead>
  <tr>
    <th>Column</th>
    <th>Encoding</th>
    <th>Description</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>dataset_version_id</td>
    <td>string</td>
    <td rowspan="5">As defined in CELLxGENE Discover <a href="https://api.cellxgene.cziscience.com/curation/ui/">data schema</a> (see &quot;Schemas&quot; section for field definitions)".</td>
  </tr>
</tbody>
</table>

Under header **Changelog**

### Version X.X.X

- Adds `dataset_version_id` to "Census table of CELLxGENE Discover datasets – `census_obj["census_info"]["datasets"]`"

**Comment by atolopko-czi** [comment]
A follow-up to this issue could be removing the source h5ad copy step from the builder.  This create af census "reproducibility" dependency on the Data Portal, since it would then be trusted to maintain the h5ad artifacts on behalf the cell census (which it now does).
