### ISSUE TITLE
Builder must error if dataset from not-supported schema version is encountered

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#634]
The Census schema specifies a dataset version schema. If the builder fetches a dataset (h5ad) via Discover API  whose schema version is different than the specified in the Census schema, it currently drops the dataset and continues the building of the Census.

The Discover API should not return datasets different than the latest dataset schema version.

Thus, if the builder encounters a dataset with an incompatible schema version, this is indicative of an upstream error. Thus the builder must stop and the issue should be diagnosed.

**Comment by bkmartinjr** [comment]
This was implemented in PR #625
