### ISSUE TITLE
Perform LTS data release `2023-07-24`

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#639]
TODOs:

- [x] Build weekly 
- [x] Spot check -- blocklist datasets were removed → @pablo-gar 
- [x] Run duplicate finder notebook `./tools/cell_dup_check/finddups.ipynb`
- [x] Run acceptances tests (only Python) → @pablo-gar 
- [x] Add summary information for this[ LTS release in the doc-site](https://chanzuckerberg.github.io/cellxgene-census/cellxgene_census_docsite_data_release_info.html#list-of-lts-census-data-releases) → @pablo-gar 
- [x] “Promote” weekly to LTS data release. → @ebezzi.  You want to make sure you give the OLD LTS release a tag/name, as well as a "do_not_delete" flag, or it WILL be deleted by build automation. 
- [x] Re-run notebooks (only python) → @ebezzi 
- [x] Do github release → @ebezzi

**Comment by pablo-gar** [comment]
Spot check completed and I have verified the block list datasets are not in the Census data version `"2023-07-25"`

https://colab.research.google.com/drive/1ImqAADk4Qrtj64yEDcaJG5WHNfiUwREZ

**Comment by pablo-gar** [comment]
No cells marked twice as `is_primary_data = True` were found after running `./tools/cell_dup_check/finddups.ipynb` PR coming with the updated notebook

**Comment by atolopko-czi** [comment]
Note that we did NOT re-alias the older `2023-05-15` LTS release. We did add the `do_not_delete` flag, which is sufficient to protect the LTS release.
