### ISSUE TITLE
Github actions should install R `tiledbsoma` releases AND from github 

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#642]
Currently the gihub action "R cellxgene.census package checks" installs `tiledbsoma` from github

https://github.com/chanzuckerberg/cellxgene-census/blob/75c2fc763a4878be7bec0c8aacae74e268ddb737/.github/workflows/r-check.yml#L25-L28

`tiledbsoma` should alsoe be installed from the releases at R-universe for now, and from CRAN when available.

**Comment by mlin** [comment]
I think we should use a build matrix to test it using both/all-of-the-above versions!

**Comment by pablo-gar** [comment]
Makes sense!
