### ISSUE TITLE
Audit R vignettes

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#683]

**Comment by mlin** [comment]
One definite pending todo: for presentation purposes we can suppress annoying warnings (e.g. about the stable census version, and the deprecated special package) by annotating the markdown blocks with `{r,message=FALSE,warning=FALSE}` instead of just `{r}`

**Comment by pablo-gar** [comment]
Thanks Mike! I did so for a few code blocks and completed the work in #686
