### ISSUE TITLE
switch our r-universe to track GitHub Releases

### ISSUE THREAD

**Issue by mlin** [chanzuckerberg/cellxgene-census#688]
get help from central infra to merge: https://github.com/chanzuckerberg/chanzuckerberg.r-universe.dev/pull/7

**Comment by mlin** [comment]
Fri evening update:

https://chanzuckerberg.r-universe.dev/builds

The `cellxgene.census` build is okay (except for Windows which isn't expected to work). The `tiledbsoma` macOS build is not because the [required version of tiledb](https://github.com/single-cell-data/TileDB-SOMA/blob/9d100df7ae90b3284c8fb2ba85f4e46df1edd488/apis/r/DESCRIPTION#L43) is not published *through the same r-universe* (nor CRAN). 

<img width="553" alt="image" src="https://github.com/chanzuckerberg/cellxgene-census/assets/356550/a2a6fb44-8f53-4f14-b1ee-f98de21f5600">

Potential solutions, in my guessed order of preference:

1. Update [our user installation instructions](https://github.com/chanzuckerberg/cellxgene-census/commit/7e614a209a1fba131d845d5e1716680df007f0c9#diff-5f415b24d01fd8c4f60ca87e8d8ab18c2069d9f5a7461c7d9f79c8a9b606e1a2R21-R26) to install tiledbsoma (and transitively tiledb) from tiledb-inc.r-universe.dev instead of ours. Like the current tiledb instruction, this would be temporary until the necessary tiledb version is up on CRAN (at which point the tiledbsoma build on chanzuckerberg.r-universe.dev should work again). 
2. Add tiledb to chanzuckerberg.r-universe.dev as well as tiledbsoma, by copying [this stanza from tiledb-inc's packages.json](https://github.com/TileDB-Inc/tiledb-inc.r-universe.dev/blob/8d383c035b0a0d7a6baeda202e1a7bbde63bffdc/packages.json#L2-L8).
3. Beg for a tiledbsoma 1.4.1 with a DESCRIPTION updated to allow the current CRAN version of tiledb. (This would potentially leave users exposed to the query hanging bug, if they don't follow our instruction to explicitly install the newest version beforehand)

**Comment by pablo-gar** [comment]
Complete in https://github.com/chanzuckerberg/chanzuckerberg.r-universe.dev/pull/8 and https://github.com/chanzuckerberg/chanzuckerberg.r-universe.dev/pull/7
