### ISSUE TITLE
float32 precision insufficient for axis stats

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene-census#714]
There are a handful of datasets in the census that expose numerical precision issues with the use of float32 data types for the `obs` axis summary stats.

For example, `obs.raw_sum` is currently a float32, and X[raw] is a float32.  There are a handful of cells that have raw counts of sufficient magnitude to overflow the 32-bit precision, resulting in an approximate value to be stored in `raw_sum`.

For example, `cbd62079-bed8-4aa1-9659-670f9cb51f9d` has one cell with a total sum of raw values equal to 30565379.  Stored as a float32, this rounds to 30565380.

```
In [126]: np.float32(30565379)
Out[126]: 30565380.0
```

Suggested fix: store all axis stats as 64 bit values.

**Comment by pablo-gar** [comment]
@mlin can you please add any R considerations? And if possible test the existence of double-precision floats?

**Comment by mlin** [comment]
According to `?double`:

<img width="533" alt="image" src="https://github.com/chanzuckerberg/cellxgene-census/assets/356550/08f26b6b-547f-4436-bf3e-bd11911726b8">

So, seems promising that this won't cause as much friction as int64s.

**Comment by bkmartinjr** [comment]
Thanks @mlin.

@pablo-gar - will convert the types to 64 bit.  This will include changes to obs:  `raw_sum`, `raw_mean_nnz` and `raw_variance_nnz`

**Comment by pablo-gar** [comment]
sounds good!
