### ISSUE TITLE
Census compatibility checks in GHA

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/cellxgene-census#717]
Write a set of tests to be run in GHA that verify the compatibility with older census versions. 
- Perform basic operations like opening the census, a dataframe, an NDArray and check that everything works.
- Use a strategy matrix to test all the previously supported version of the Census.

**Comment by metakuni** [comment]
@ebezzi , can this be closed?

**Comment by bkmartinjr** [comment]
@ebezzi @pablo-gar - I think this is done.  Can this be closed?

**Comment by bkmartinjr** [comment]
Closing this as complete.  @ebezzi - please re-open if you see a gap in our current actions.
