### ISSUE TITLE
Develop a proposal for a design of a Census tokenizer that creates modeling-ready data for Geneformer 

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#727]
### Relevance

Geneformer was identified as a potential model that could offer Census-integrated assets and/or models for the following high-priority Census work: [The Census includes pre-computed results with specific focus on integration algos which simplify access, usability and expand the user base (e.g. embeddings, pre-trained models, summary statistics).](https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/gh/chanzuckerberg/single-cell/506) In particular for the following areas.

1. Embedding generation.
2. Cell type prediction.
3. Identification of key genes involved disease.

In addition there are other promising areas where Geneformer can provide insights to Census users. As such providing modeling-ready Census data for Geneformer is valuable for internal and external use of Census data.

### Tokenization

A key aspect of Geneformer is that it requires **tokenized** data after data normalization. The tokenization involves the following steps:

- Normalize cells by library size (row sums)
- Normalize cells by median expression per gene across all cells at ["Genecorpus" data](https://huggingface.co/datasets/ctheodoris/Genecorpus-30M/tree/main/example_input_files)
- Rank genes per cell, high-to-low. 
- Convert genes to integer tokens
- Export to hugging face `Dataset` class.

### The problem: lack of a scalable tokenizer.

[The current tokenizer provided by Geneformer](https://huggingface.co/ctheodoris/Geneformer/blob/main/geneformer/tokenizer.py) has proven hard to scale in the context of Census during internal testing. This is due to the following pain points of the tokenizer:

1. It is implemented for loom, so Census data needs to be exported to AnnData and then saved as loom.
2. It makes a hugging face Dataset using the `Dataset.from_dict()` method which somehow cannot convert large matrices due to an error in the inference of token vector encoding (encoded as int16 rather than int64).
4. It calculates token sizes after creating the dataset (using `.map()`) and it frequently breaks with multiprocessing of the length calculation.
5. It creates tokens in an inefficient way for sparse matrices, not taking advantage of the csr format, which Census guarantees. 

## Definition of Done

A proposed design of a Census tokenizer that:

- Performs iterative creation of tokenized `Datasets` for memory-efficient tokenization.
- Works natively with Census (`tiledbsoma`) 
- It's flexible and extensible for future potential different tokenization methods different from Geneformer. 

## Example tokenizer for in-memory Census data (from anndata)

This implementation of a tokenizer has been used internally as workaround:

[census_adata_tokenizer.py](https://gist.github.com/pablo-gar/7cbba76caa3f3cfb7b5ebf96b37d2644)

- Does the gene expression normalization in sparse format, increasing efficiency.
- Calculates token’s length on the fly during token generation.
- Stores tokens on pandas data frame rather than dictionary
- Uses method `from_pandas()` to create Dataset, this preserves int64 tokens and scales well to large datasets

**Comment by super-dainiu** [comment]
Hi, may I have a minor suggestion? 

Since the rank value encoding seems to be excellent in modeling scRNA-seq data, is that possible that the GeneformerTokenizer will tokenize the Anndata into a list of Ensembl IDs (without truncation) instead of input ids? This will give user more degrees of freedom to explore the dataset (i.e. different ways of tokenization).

From my experience, we can easily design a tokenizer that tokenizes and truncates a sequence of Ensembl IDs into input_ids. And we can also extend our vocabulary or tokenization methods as we wish.

**Comment by pablo-gar** [comment]
@super-dainiu we have completed this work we indeed enable for any custom tokenization mode (see the [abstract class](https://github.com/chanzuckerberg/cellxgene-census/blob/main/api/python/cellxgene_census/src/cellxgene_census/experimental/ml/huggingface/cell_dataset_builder.py) and the implementation of [Geneformer's tokenizer](https://github.com/chanzuckerberg/cellxgene-census/blob/main/api/python/cellxgene_census/src/cellxgene_census/experimental/ml/huggingface/geneformer_tokenizer.py)). We would love to chat with you, please email me at pgarcia-nieto@chanzuckerberg.com in case you'd be interested in chatting to see how we can best support your use cases.

I'm closing the issue as completedby #762
