### ISSUE TITLE
python3.10 CI unit tests unpredictably fail

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#741]
See these examples:

https://github.com/chanzuckerberg/cellxgene-census/actions/runs/5781109247/job/15665732341
https://github.com/chanzuckerberg/cellxgene-census/actions/runs/5777910151/job/15658572424
https://github.com/chanzuckerberg/cellxgene-census/actions/runs/5781109247/job/15665732341

Usually, when manually re-run this GHA succeeds.

**Comment by bkmartinjr** [comment]
Root cause:
* Unit tests randomly generate the count matrix for test runs of the census build/validate methods
* In the case where any cell has no counts > 0 (i.e., nnz==0 for that cell), the builder will incorrectly calculate a number of axis stats
* and the unit test will fail
