### ISSUE TITLE
[builder] Failed at consolidation step

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/cellxgene-census#744]
Failed at consolidation step with `tiledb.cc.TileDBError: [TileDB::Reader] Error: Incorrect unfiltered tile size allocated.` [[logs](https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logsV2:log-groups/log-group/%2Fcellxgene-census-builder-prod/log-events/cellxgene-census-builder-prod%2Fdefault%2F2bfcf805029e4a19824294d0419d86bf)]

12 of 13 consolidation processed completed successfully.
The failed consolidation was for: `file:///census-build/2023-08-28/soma/census_data/homo_sapiens/ms/RNA/X/normalized`

**Comment by atolopko-czi** [comment]
Fix is in place. Will wait until Monday's scheduled run to confirm success before closing out this issue.

**Comment by atolopko-czi** [comment]
2023-09-04 build was successful, so closing this issue.

**Comment by atolopko-czi** [comment]
2023-09-12 build failed again with same error ([logs](https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logsV2:log-groups/log-group/%2Fcellxgene-census-builder-prod/log-events/cellxgene-census-builder-prod%2Fdefault%2F63a21f7fdf2e46faaaf8e3915740aecd)). So not likely caused by disk space.

**Comment by atolopko-czi** [comment]
- [ ] Share the following with TileDB at https://czi-sci.slack.com/archives/C013K0JB8F8/p1694537135163599?thread_ts=1694533729.655039&cid=C013K0JB8F8
* tiledbsoma.show_package_versions() as used by the process doing the consolidation
* re-run with "config.logging_level": 5 in the Ctx config and send me that

**Comment by atolopko-czi** [comment]
https://github.com/single-cell-data/TileDB-SOMA/issues/1670

**Comment by atolopko-czi** [comment]
A single, ad hoc builder run _succeeded_ on consolidation (with level 5 tiledb log level in place), but this did not reproduce the error. Running second attempt of consolidation for just `homo_sapiens/../X/normalized`.

Saved pre-consolidated fragments on this [volume](https://us-west-2.console.aws.amazon.com/ec2/home?region=us-west-2#VolumeDetails:volumeId=vol-057749436bf0f2eca) at `2023-09-12/soma.pre_consolidate/census_data/homo_sapiens/ms/RNA/X/normalized`  in case they are of use for future investigation.

Should proceed to plan B: adding tiledb log level to builder so we can catch debug on subsequent run. Proposing this (untested) [change](https://github.com/chanzuckerberg/cellxgene-census/pull/767), which adds ability to override _any_ tiledb config defaults in the builder by accepting json as a config param.

**Comment by atolopko-czi** [comment]
> Running second attempt of consolidation for just homo_sapiens/../X/normalized.

This also succeeded, fwiw.

**Comment by atolopko-czi** [comment]
erroenous close

**Comment by bkmartinjr** [comment]
per single-cell-data/TileDB-SOMA#1670 a fix is likely forthcoming in TileDB core 2.17.2

**Comment by bkmartinjr** [comment]
@ebezzi @atolopko-czi - this seems to have disappeared.  If you agree, can we close?

**Comment by ebezzi** [comment]
Yeah, I haven't seen it in a while. Let's close!
