### ISSUE TITLE
Demo notebooks can and will get out of sync from stable releases.

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#75]
As changes are introduced in the cell census or SOMA codebases, the demo notebooks get updated, at which point the notebooks can become incompatible with the current pypi release.

This is a problem because users are likely to rely on the notebooks to onboard on the Cell Census, AND most users are likely to use the pypi release.

Abstract solution: A copy of notebooks need to be fixed to a release version.

Potential practical solutions to explore:
- Notebooks live in a  versioned doc site (e.g. readthedocs)

@bkmartinjr @atolopko-czi Please add any other suggestions you may have

**Comment by atolopko-czi** [comment]
For now, I think we can just add a script that is used to manually update the scripts in place using:
```
pip install nbconvert
jupyter-nbconvert --to notebook --inplace --execute api/python/notebooks/*_demo/*.ipynb
```
https://nbconvert.readthedocs.io/en/latest/usage.html#notebook-and-preprocessors
https://nbconvert.readthedocs.io/en/latest/usage.html#converting-multiple-notebooks

The script could also generate a PR (using `gh pr create`, e.g.). 

By convention, this script would be run as a final step in the 1) cell census build process and 2) API release process. We would just update our documentation to include this new step in each case.

Ultimately, we can have this run in GHA and invoke it via GH API (using a `workflow_dispatch`-triggered workflow), but that may not be the worth the effort yet.
