### ISSUE TITLE
`cellxgene_census.get_anndata()` should have an argument `X_layers`

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#760]
To load any additional layers from Census to an AnnData via `cellxgene_census.get_anndata()`, the method should have an argument `X_layers`

**Comment by bkmartinjr** [comment]
There already is an `X_name` which provides the ability to ask for an alternate layer - how is this different?

**Comment by pablo-gar** [comment]
Goes directly into `X_layers` arg of `to_anndata` i.e. adds those as additional layers under `AnnData.layers` on top of `X_name` that goes to `AnnData.X`

**Comment by bkmartinjr** [comment]
got it - so the use case is exporting multiple layers.
