### ISSUE TITLE
Create a process to train an scVI model across all unique human and mouse cells.

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#777]
The process should be CLI-driven, stand-alone python script(s) to execute the workflow. Only input is a YAML config to set the params.

The process should accomplish the following

**1. Pre-process data**

For both mouse and human an anndata should be created with the following specification:

1. Selecting only primary data and and cells with nnz >= `min_genes` via `get_anndata`
2. Select `top_n_hvg` highly variable genes with `hvg_batch`

Parameters:
- `top_n_hvg`: defaults to 8000
- `hvg_batch`: defaults to "dataset_id", when #788 is completed then "suspension_type" + "assay"
- `min_genes`: defaults to 300

**2. Training scVI**
A process that trains two scVI models (one per organism) using the pre-processed data with the following steps:
1. Loads anndata and sets batch variable.
2. Sets up model (`scvi.model.SCVI`).
3. Trains model (`SCVI.train`)
4. Saves the model (`SCVI.save`)

Parameters:
- Anndata loads `batch_variable`: defaults to concatenation of dataset_id + assay + suspension_type + donor_id
- `scvi.model.SCVI`
   - `n_hidden`: 512
   - `n_latent`: 200
   - `n_layers`: 1
   - `dropout_rate`: defaults to 0.1
 - `SCVI.train`
   - `max_epochs`: 20
   - `batch_size`: 1048
   - `plan_kwargs`: {"lr": 1e-4}
   - ` early_stopping`: True
   -  `early_stopping_patience`: 2
   - `early_stopping_monitor`: "validation_loss"
   - `check_val_every_n_epoch`: 1
   - ` train_size`: 0.95

**Comment by pablo-gar** [comment]
Update parameters based on [auto tuner analysis](https://github.com/YosefLab/census-scvi/blob/main/experiments/autotune/notebooks/2023_09_autotune_report.ipynb) by Yosef lab

- Anndata loads `batch_variable`: defaults to concatenation of dataset_id + assay + suspension_type + sample_id
- `scvi.model.SCVI`
   - `n_hidden`: defaults to 512
   - `n_latent`: 200
   - `n_layers`: 1
   - `dropout_rate`: defaults to 0.1
 - `SCVI.train`
   - `max_epochs`: 10
   - `batch_size`: 1048
   - "plan_kwargs": {"lr": 1e-4}

**Comment by pablo-gar** [comment]
Two changes reflected now in the ticket:

- `top_n_hvg`:  8000
- `hvg_batch`: defaults to "dataset_id", when #788 is completed then "suspension_type" + "assay"

**Comment by martinkim0** [comment]
Even though we've seen models converging around epoch 10, I'd recommend training a bit longer and using early stopping to see if there's any changes with the new data release:
```
SCVI.train
- max_epochs=20
- batch_size=1048
- plan_kwargs={"lr": 1e-4}
- early_stopping=True
- early_stopping_patience=2
- early_stopping_monitor="validation_loss"
- check_val_every_n_epoch=1
- train_size=0.95
```
I'd also recommend logging with TensorBoard (which logs locally only, so no privacy concern I believe). You can see an example here: https://github.com/YosefLab/census-scvi/blob/main/experiments/hlca/02_train_base_model.py#L72 
It makes it easier to monitor training in real time.

**Comment by ebezzi** [comment]
Hey @martinkim0, the early stopping condition you suggested don't seem to work as `early_stopping_monitor=validation_loss` is not accepted. PyTorch reports those as the available metrics:

`kl_weight`, `train_loss`, `train_loss_step`, `train_loss_epoch`, `elbo_train`, `reconstruction_loss_train`, `kl_local_train`, `kl_global_train`

but the scvi docs also mention that they depend on the training plan class used. Am I missing something?

**Comment by martinkim0** [comment]
@ebezzi Mm interesting. Could you double check that `check_val_every_n_epoch=1` is being passed into the train function? Otherwise I'd have to take closer look at the traceback + code. Thanks!

**Comment by ebezzi** [comment]
We synced with Martin in a separate channel and he found out that the issue arises with multi-GPU training. Will keep this thread updated when a solution is found.

**Comment by pablo-gar** [comment]
@ebezzi for testing purposes let's try with 10 epochs and excluding `early_stopping` that will give us a baseline for how long it will take

**Comment by pablo-gar** [comment]
completed
