### ISSUE TITLE
Define a path to promote a the functionality of `cellxgene_census.experimental.util._csr_iter.X_sparse_iter` as stable

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#794]
## Description

`cellxgene_census.experimental.util._csr_iter.X_sparse_iter` has been found to be of great utility for both internal and external cases. Since it has not been advertised and it is experimental, users have mentioned the need to gain the functionality that this method has.

## Context

The recurrent issue is the following:

- I need a memory efficient way to access sparse matrices for downstream analysis. I often require:
   - An iterator that provides csr chunks
   - Full rows per chunk, i.e. no disjoint chunks. 
   - Re-indexed positional indices, i.e. no `soma_joinids`

## Potential solutions

- Promote this method as stable in `cellxgene_census`
- Find a path to move functionality down to `tiledbsoma`. Probably requires more design work to ensure we have the best way to integrate with `tieldbsoma`

**Comment by bkmartinjr** [comment]
@pablo-gar - see single-cell-data/TileDB-SOMA#1503

**Comment by bkmartinjr** [comment]
this is resolved by single-cell-data/TileDB-SOMA#1792
