### ISSUE TITLE
Store organism ontology term ID in census object

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/cellxgene-census#796]
## Description

It would be convenient if Census contained the organism ontology term ID in the corresponding organism's census object. 

## Context

I am building the WMG snapshot from census and need to maintain a mapping between census organism keys and their ontology term IDs (WMG snapshot requires the term IDs, not the labels):
`{'homo_sapiens': 'NCBITaxon:9606', 'mus_musculus': 'NCBITaxon:10090'}`

## Impact

It is inconvenient to need to maintain a separate mapping table, especially if we add support for more organisms.

**Comment by pablo-gar** [comment]
Let's add another mapping table to `census["info"]` with the following schema specification:

#### Census table of organisms – `census_obj["census_info"]["organisms"]` – `SOMADataFrame`

Information about organisms whose cells are included in the Census MUST be included in a table modeled as a `SOMADataFrame`. Each row MUST correspond to an individual organism with the following columns:

<table>
<thead>
  <tr>
    <th>Column</th>
    <th>Encoding</th>
    <th>Description</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>organism_ontology_term_id</td>
    <td>string</td>
    <td>As defined in the CELLxGENE dataset schema.</td>
  </tr>
  <tr>
    <td>organism_label</td>
    <td>string</td>
    <td>Human-readable label as given by the ontology.</td>
  </tr>
  <tr>
    <td>organism</td>
    <td>string</td>
    <td>Machine-friendly label used to name the SOMA Experiments, see below  <a href="#census-data--census_objcensus_dataorganism--somaexperiment">Census Data section.</a></td>
  </tr>
</tbody>
</table>

An example of this `SOMADataFrame` is shown below:

<table>
<thead>
  <tr>
    <th>organism_ontology_term_id</th>
    <th>organism_label</th>
    <th>label</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td>NCBITaxon:9606</td>
    <td>Homo sapiens</td>
    <td>homo_sapiens</td>
  </tr>
  <tr>
    <td>NCBITaxon:10090</td>
    <td>Mus musculus</td>
    <td>mus_musculus</td>
  </tr>
</tbody>
</table>
