### ISSUE TITLE
feat: the normalized layer should contain gene-length normalized counts from SmartSeq data

### ISSUE THREAD

**Issue by atarashansky** [chanzuckerberg/cellxgene-census#813]
The normalized layer is currently not usable for cells coming from SmartSeq assays. SmartSeq assays need to normalize raw counts by gene lengths prior to sum normalization.

When building the normalized layer, Census should be performing gene length normalization for applicable cells.

**Comment by pablo-gar** [comment]
Solution:

For cells of `assay` "EFO:0008930", "EFO:0008931", "EFO:0700016". The normalized  cell vector should be:

1. Divide each value in the vector by  its corresponding `var["gene_length"]`
    i.e `a[i,:] = X["raw"][i,:] / obs["gene_length"]` for cell `i`
3. Then, divide by the sum of these values 
   i.e.`normalized[i:] = a[i,:] / sum(a[i,:])`

**Comment by bkmartinjr** [comment]
Resolved by #884
