### ISSUE TITLE
deprecate and remove X_sparse_iter when tiledbsoma blockwise iterators are available

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene-census#832]
When SOMA support for blockwise iterators are released:

- [x] deprecate cellxgene_census.experimental.util.X_sparse_iter
- [x] port all uses to blockwise iterators:
    - [x] geneformer/mul
    - [x] find_dups notebook
    - [x] unit tests
    - [x] pca notebook
- [x] remove from the cellxgene_census package

Blockwise iterators will ship in TileDB-SOMA 1.5, so this needs to be deprecated in cellxgene-census version 1.8 and removed in 1.9

**Comment by mlin** [comment]
I have to update the geneformer tokenizer.
