### ISSUE TITLE
Automate acceptance/expensive tests

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/cellxgene-census#856]
## Motivation

Currently acceptance tests need to be run manually on a large instance. They're currently run before we release an LTS but not when we release a new Census version. It would be good to run them automatically.

## Proposals

1. Create and push a script that sets up the environment, runs the tests and uploads the results to a permanent location (e.g. an S3 bucket). This isn't automation, but it will at least make the process less cumbersome.
2. Create a Batch job that acts as a test runner. This has operational overhead (requires infra and to Dockerize the test runner itself), but it is a viable solution. 
3. Run the tests in GHA using a custom runner. Also a viable solution with less overhead, but the feasibility needs to be verified.

**Comment by bkmartinjr** [comment]
Resolved by #897
