### ISSUE TITLE
Dataset appears incomplete

### ISSUE THREAD

**Issue by dominikglodzikhms** [chanzuckerberg/cellxgene-census#862]
## Describe the bug

Hi 'cellxgene' team! Thank you for setting up this fantastic platform.

I have started analyzing the data available [here](https://cellxgene.cziscience.com/e/b252b015-b488-4d5c-b16e-968c13e48a2c.cxg/). However, several genes I tried are not expressed at all. 

## To Reproduce
For example, I selected ATM, a gene that is widely expressed across tissues, but in this dataset, it appears not to be expressed at all.

![Screen Shot 2023-11-17 at 3 18 31 PM](https://github.com/chanzuckerberg/cellxgene-census/assets/82227017/97b238b1-7117-4920-bf6e-758a305acb7e)

It could be that the data is not available for some genes, or it’s an error in the portal. Do you have any insight about which might be the case? 

## Expected behavior

If a gene is not included in the data set, I would prefer this was explicitly stated.

## Environment

MacOS 11.7.10
Chrome 119

**Comment by MaximilianLombardo** [comment]
Hi @dominikglodzikhms thanks for flagging this! confirming that I can the issue as well, although the error manifests itself a bit differently on my end (see below). Flagging for the team in this issue. I tagged you in the follow up issue (also mentioned above)

P.S. this repo is more for the Census API. In the future, you might consider submitting issues for issues with the data portal in the [single-cell-data-portal](https://github.com/chanzuckerberg/single-cell-data-portal) repo.

**Comment by MaximilianLombardo** [comment]
Closing this issue to avoid duplication since the conversation has been moved to [here](https://github.com/chanzuckerberg/single-cell-curation/issues/693)
