### ISSUE TITLE
[docs] Docsite workflow doesn't pick the correct version

### ISSUE THREAD

**Issue by ebezzi** [chanzuckerberg/cellxgene-census#865]
The GHA workflow to generate the docsite, when run on a new tag, does not capture the latest tag. Suggestions:
1. Test the code in docs/conf.py on a locally generated tag and see what happens
2. Add logs to see which tags are available when running the workflow.

Until this is fixed, the docsite needs to be run manually after a deployment.

**Comment by pablo-gar** [comment]
Completed
