### ISSUE TITLE
Add `obsm_layers` parameter to `get_seurat` and `get_single_cell_experiment`

### ISSUE THREAD

**Issue by pablo-gar** [chanzuckerberg/cellxgene-census#873]
With the following signature

`obsm_layers = FALSE`

And the following doc string

```
@param obsm_layers Names of arrays in obsm to add as the cell embeddings; pass FALSE to suppress loading in any dimensional reductions.
```

**Comment by mlin** [comment]
@pablo-gar any specific reason for defaulting to FALSE as opposed to NULL? (Noting that the `SOMAExperimentAxisQuery` methods we're passing through to default to NULL)

**Comment by pablo-gar** [comment]
Completed at #887
