### ISSUE TITLE
Remove explicit storage of source h5ad files as cell census data artifacts

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/cellxgene-census#89]
Depends on https://github.com/chanzuckerberg/cell-census/issues/6

Once the Cell Census metadata includes references to persistent H5AD files, maintained by CELLxGENE Data Portal, the builder no longer needs to store the source H5ADs as part of the Cell Census data.

**Comment by pablo-gar** [comment]
Does this have any implications on API functionality that fetches source h5ads? `cell_census.get_source_h5ad_uri`

**Comment by bkmartinjr** [comment]
> Does this have any implications on API functionality that fetches source h5ads? cell_census.get_source_h5ad_uri

Yes, it will require that we revise / release a new cell_census package, as the current API implementation has hard-wired assumptions about the data location.

However, this change should be backward compatible, and not require end-user code changes (just a package version update)

**Comment by brianraymor** [comment]
> it should be deprecated in favor of the Discover API that lets a user fetch an H5AD given a dataset_id/dataset_version_id pair.

Clarified in slack that the Discover API is not needed for this scenario. The request is a simple GET from CloudFront based on the dataset version uuid.

**Comment by bkmartinjr** [comment]
Obsoleted by #935 - will not fix.
