### ISSUE TITLE
Pass custom User-Agent header for all Dataset download requests from user package and Builder

### ISSUE THREAD

**Issue by danieljhegeman** [chanzuckerberg/cellxgene-census#926]
(Related #257)

([Related Analytics script changes](https://github.com/chanzuckerberg/single-cell-analytics/pull/225))

We want to have a way to exclude all requests from Census-related downloads from Analytics assessment of cxg Dataset downloads. The easiest way to do this is to pass a custom `User-Agent` header for download requests that we control. I recommend we include:
- a common flag portion `ignore` that can be added to other services, or can even easily be included in custom bulk-downloading scripts, which will not require changes to the Analytics script in order to acknowledge
- a project identifier `census`
- an actor identifier (for Census: `builder` or `user`)
- environment identifier

Therefore, a User-Agent value might be `ignore-census-builder-prod`; this request would then be filtered out by the Analytics script when it reads from Cloudfront logs. cc @ainfeld @bkmartinjr 

Tasks: 
- [x] Update all BUILDER requests to `https://datasets...` endpoints to include the aforementioned header
- [ ] Update all USER requests to `https://datasets...` endpoints to include the aforementioned header

**Comment by bkmartinjr** [comment]
Builder header will be `census-builder-(dev|staging|prod)`

**Comment by bkmartinjr** [comment]
@danieljhegeman - first task is done.  I'm not sure if the second task is relevant given our slack conversation - will let you decide if this issue is resolved or still has work to be done.

**Comment by bkmartinjr** [comment]
Closing in favor of #997
