### ISSUE TITLE
add retries on mirrors.json/requests.json fetching

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene-census#933]
Our GHA's periodically fail due to network-level failures in fetching mirrors.json/requests.json, when access via the cellxgene-census R and/or Python packages.  It is likely that other users see similar issues, and that they are caused by (inevitable & occasional) network instability.

Suggested fix:  add a small number of retries, with appropriate backoff, to the fetch of release.json and mirrors.json

For Python, which uses the `requests` package, there is already built-in support that [can be enabled - example here](https://requests.readthedocs.io/en/latest/user/advanced/?highlight=Retry#example-automatic-retries).

To do:
- [ ] Python package retries
- [ ] R package retries

**Comment by pablo-gar** [comment]
We'll monitor if caching has not fully solved this
