### ISSUE TITLE
Fix Geneformer instructions 

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/cellxgene-census#949]
User reports:
> I'm running into some errors for Geneformer when following the instructions here. It seems like the model isn't accessible: `fatal error: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied` and I get some other errors when trying to import packages

The AccessDenied error is likely due to the [Geneformer instructions](https://chanzuckerberg.github.io/cellxgene-census/notebooks/analysis_demo/comp_bio_geneformer_prediction.html) not specifying the `--no-sign-request` option.

**Comment by mlin** [comment]
This should be fixed in the upcoming release by https://github.com/single-cell-data/TileDB-SOMA/pull/2049

**Comment by metakuni** [comment]
> This should be fixed in the upcoming release by [single-cell-data/TileDB-SOMA#2049](https://github.com/single-cell-data/TileDB-SOMA/pull/2049)

@mlin , could you close this ticket on confirmation? 🙏
