### ISSUE TITLE
[python] dependency pins are overly specific

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene-census#968]
The package experimental optional dependencies hard-pin a number of packages. It would be ideal if we could loosen these version dependencies to what is actually needed, allowing downstream users a bit more flexibility in choosing package versions.

Currently the required dependencies follow this style, but the optional do not.  Examples:

```
dependencies= [
    "anndata",
    "numpy>=1.21,<1.25",  # numpy is constrained by numba and the old pip solver
    "requests",
    "typing_extensions",
    "s3fs>=2021.06.1",
]

[project.optional-dependencies]
experimental = [
    "torch==2.0.1",
    "torchdata==0.6.1",
    "scikit-learn==1.3.1",
    "scikit-misc==0.2.0",
    "psutil==5.9.5",
    "datasets~=2.14",
    "tdigest~=0.5",
]
```

In an ideal world, would like something like `pytorch>=2.0.0` or some such....  Especially for the very general packages such as `datasets` and `psutil` which are used downstream

**Comment by mlin** [comment]
The two I put in could be relaxed to `"datasets~=2", "tdigest>=0.5"`; defer to @atolopko-czi on the others

**Comment by bkmartinjr** [comment]
@mlin - that would be a win.  If you have time, please submit a PR (or LMK if you don't and I'll submit a PR).  I'd like to get it into this upcoming release if  possible.  CC: @ebezzi
